### ISSUE TITLE
Build failure with custom build command for nss_sys

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/application-services#1012]
Build failure trying to assemble reference browser with a substitution build for arm.

```
Compiling reqwest v0.9.15
   Compiling nss_sys v0.1.0 (/Users/jalmeida/src/application-services/components/support/rc_crypto/nss_sys)
error: failed to run custom build command for `nss_sys v0.1.0 (/Users/jalmeida/src/application-services/components/support/rc_crypto/nss_sys)`
process didn't exit successfully: `/Users/jalmeida/src/application-services/target/debug/build/nss_sys-05d0f84fbef5a249/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=NSS_DIR
cargo:rerun-if-changed=bindings.toml

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Rust: `rustc 1.34.0 (91856ed52 2019-04-10)`

**Comment by jonalmeida** [comment]
To update the ticket, I've tried running `libs/bootstrap-desktop.sh` and then `libs/build-all.sh android` scripts as suggested, but the build-all script fails:
```
+ NSS_SRC_PATH=/Users/jalmeida/src/application-services/nss-3.43
./patch-nss-src.sh "${NSS_SRC_PATH}"
+ ./patch-nss-src.sh /Users/jalmeida/src/application-services/nss-3.43
./libs/build-all.sh: line 64: ./patch-nss-src.sh: No such file or directory
```

(nss from brew is in my env PATH as well)

**Comment by vladikoff** [comment]
with BACKTRACE:

```
> Task :application-services:fxa-client-library:cargoBuildArm
   Compiling nss_sys v0.1.0 (/Users/vladikoff/mozilla/application-services/components/support/rc_crypto/nss_sys)
   Compiling viaduct v0.1.0 (/Users/vladikoff/mozilla/application-services/components/viaduct)
error: failed to run custom build command for `nss_sys v0.1.0 (/Users/vladikoff/mozilla/application-services/components/support/rc_crypto/nss_sys)`
process didn't exit successfully: `/Users/vladikoff/mozilla/application-services/target/debug/build/nss_sys-66cf2bb9f0e29cbe/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=NSS_DIR
cargo:rerun-if-changed=bindings.toml

--- stderr
/Users/vladikoff/mozilla/android-ndk-r15c/sysroot/usr/include/linux/types.h:21:10: fatal error: 'asm/types.h' file not found
/Users/vladikoff/mozilla/android-ndk-r15c/sysroot/usr/include/linux/types.h:21:10: fatal error: 'asm/types.h' file not found, err: true
thread 'main' panicked at 'unable to generate bindings: ()', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:312
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/744b374ab6197d7d06994b06a9598bbd3210efce/src/libcore/macros.rs:17
   9: <core::result::Result<T, E>>::expect
             at /rustc/744b374ab6197d7d06994b06a9598bbd3210efce/src/libcore/result.rs:825
  10: build_script_build::build_bindings
             at components/support/rc_crypto/nss_sys/build.rs:106
  11: build_script_build::main
             at components/support/rc_crypto/nss_sys/build.rs:63
  12: std::rt::lang_start::{{closure}}
             at /rustc/744b374ab6197d7d06994b06a9598bbd3210efce/src/libstd/rt.rs:64
  13: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  14: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:87
  15: std::panicking::update_count_then_panic
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  16: std::rt::lang_start
             at /rustc/744b374ab6197d7d06994b06a9598bbd3210efce/src/libstd/rt.rs:64
  17: build_script_build::get_ios_sdk_root

warning: build failed, waiting for other jobs to finish...
error: build failed

> Task :application-services:fxa-client-library:cargoBuildArm FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':application-services:fxa-client-library:cargoBuildArm'.
> Process 'command 'cargo'' finished with non-zero exit value 101

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by bug-mirror** [comment]
cc @jonalmeida , do you still have this problem?
