### ISSUE TITLE
Intermittent "Missing HTTP status" errors when syncing in the emulator

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#1096]
Occasionally, I'll see a Viaduct stack trace like this when running Fenix in the emulator:

```
2019-04-25 21:43:33.185 9108-9267/org.mozilla.fenix.debug E/viaduct::backend::ffi: Missing HTTP status
2019-04-25 21:43:33.185 9108-9267/org.mozilla.fenix.debug E/fxa_client::errors: FxA error `viaduct::Error`: BackendError("Missing HTTP status")
2019-04-25 21:43:33.185 9108-9267/org.mozilla.fenix.debug W/fxa_client::ffi: Network error: Error(
    Network error: Backend error: Missing HTTP status)
2019-04-25 21:43:33.194 9108-9273/org.mozilla.fenix.debug E/FirefoxAccountStateMachine: Failed to get profile for authenticated account
    mozilla.appservices.fxaclient.FxaException$Network: Network error: Backend error: Missing HTTP status
        at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:43)
        at mozilla.appservices.fxaclient.FirefoxAccount.getProfile(FirefoxAccount.kt:514)
        at mozilla.components.service.fxa.FirefoxAccount$getProfile$1.invokeSuspend(FirefoxAccount.kt:123)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

I've noticed this happens more often after waking from sleep, even after my laptop is back online. Restarting the emulator usually makes it go away, so maybe it's just a quirk? But I thought I'd get the bug on file in case we aren't handling a network error correctly or something.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-67)
┆Story Points: 3
┆Epic: [Q3 2.4] Fenix 2.0 Support

**Comment by thomcc** [comment]
This is probably what happens if we hit https://github.com/mozilla/application-services/blob/c1fe5367e52830f7e8826cb0d03826291cc10294/components/viaduct/android/src/main/java/mozilla/appservices/httpconfig/HttpConfig.kt#L143-L145

Some logging would probably help a lot here, it's tricky to add though.

**Comment by rfk** [comment]
Is there anything we need to do here ahead of Fenix release?

**Comment by vladikoff** [comment]
Sentry https://sentry.prod.mozaws.net/operations/fenix/issues/5810945/?query=is:unresolved%20http%20status

**Comment by mhammond** [comment]
It looks like Lina's traceback is from https://github.com/mozilla-mobile/android-components/blob/master/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt#L401 - the exception is handled, so I don't expect this to make it to sentry.

However, the sentry one is very similar, but probably via https://github.com/mozilla-mobile/android-components/blob/master/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt#L385 - there's no exception handler here.

ISTM that this almost certainly is a real network error, and it appears to be correctly reported as a NetworkError by FxA. So ISTM there's actually nothing for app-services to do here, but android-components does need FxA integration hardened so it more gracefully handles transient network errors.

@grigoryk thoughts?

**Comment by mhammond** [comment]
It's trivial to reproduce a network related crash, so I'm opening an a-c issue.

**Comment by thomcc** [comment]
@linacambridge reported this never recovering (which would be very bad), and it's still us failing to report a network error properly (it's not a missing HTTP status).

**Comment by mhammond** [comment]
> @linacambridge reported this never recovering (which would be very bad),

Yes, I agree that would be bad.

> and it's still us failing to report a network error properly (it's not a missing HTTP status).

If the root cause really is a network error then that's unfortunate, but not necessarily a super-high priority. I'll try and reproduce what lina reported.

**Comment by mhammond** [comment]
I can't reproduce Lina's issue exactly - the profile fetch in her traceback happens *after* the crash reported by sentry. Maybe in Lina's case the profile was being refreshed? Anyway, the closest I can get is to set a breakpoint where we fetch the profile and disable the network before resuming - I then see the same traceback. After restoring the network and waiting a while, I see in logcat:

```
2019-05-27 17:40:27.795 11840-12287/org.mozilla.fenix.debug I/FxaEventsManager: Refreshing device list...
2019-05-27 17:40:27.804 11840-12381/org.mozilla.fenix.debug D/fxaclient_ffi: fxa_get_devices
2019-05-27 17:40:28.540 11840-12381/org.mozilla.fenix.debug I/FxaEventsManager: Refreshed device list; saw 6 device(s).
2019-05-27 17:40:28.544 11840-12497/org.mozilla.fenix.debug D/FxaEventsManager: poll
2019-05-27 17:40:28.552 11840-12844/org.mozilla.fenix.debug D/fxaclient_ffi: fxa_poll_device_commands
2019-05-27 17:40:28.832 11840-12844/org.mozilla.fenix.debug D/fxaclient_ffi: fxa_to_json
```

so it looks like it does recover for me.

**Comment by grigoryk** [comment]
@mhammond fxa network issues are currently not handled in a-c. They're being taken care of in  https://github.com/mozilla-mobile/android-components/pull/3093
