### ISSUE TITLE
Substitution build failing in fenix

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#1651]
cc @vladikoff
```
08-21 17:31:35.012 11773 11773 E AndroidRuntime: java.lang.UnsatisfiedLinkError: Error looking up function 'fxa_disconnect': undefined symbol: fxa_disconnect
08-21 17:31:35.012 11773 11773 E AndroidRuntime: 	at com.sun.jna.Function.<init>(Function.java:251)
08-21 17:31:35.012 11773 11773 E AndroidRuntime: 	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:594)
08-21 17:31:35.012 11773 11773 E AndroidRuntime: 	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:570)
08-21 17:31:35.012 11773 11773 E AndroidRuntime: 	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:556)
08-21 17:31:35.012 11773 11773 E AndroidRuntime: 	at com.sun.jna.Library$Handler.invoke(Library.java:228)
08-21 17:31:35.012 11773 11773 E AndroidRuntime: 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
08-21 17:31:35.012 11773 11773 E AndroidRuntime: 	at $Proxy5.fxa_disconnect(Unknown Source)
08-21 17:31:35.012 11773 11773 E AndroidRuntime: 	at mozilla.appservices.fxaclient.FirefoxAccount.disconnect(FirefoxAccount.kt:342)
08-21 17:31:35.012 11773 11773 E AndroidRuntime: 	at mozilla.components.service.fxa.FirefoxAccount$disconnectAsync$1$2.invoke(FirefoxAccount.kt:260)
08-21 17:31:35.012 11773 11773 E AndroidRuntime: 	at mozilla.components.service.fxa.FirefoxAccount$disconnectAsync$1$2.invoke(FirefoxAccount.kt:31)
08-21 17:31:35.012 11773 11773 E AndroidRuntime: 	at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:31)
08-21 17:31:35.012 11773 11773 E AndroidRuntime: 	at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:57)
08-21 17:31:35.012 11773 11773 E AndroidRuntime: 	at mozilla.components.service.fxa.FirefoxAccount$disconnectAsync$1.invokeSuspend(FirefoxAccount.kt:259)
08-21 17:31:35.012 11773 11773 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-21 17:31:35.012 11773 11773 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
08-21 17:31:35.012 11773 11773 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
08-21 17:31:35.012 11773 11773 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
08-21 17:31:35.012 11773 11773 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-318)

**Comment by grigoryk** [comment]
Running this on arm device. Hitting error when pressing remove account.

**Comment by eoger** [comment]
From meeting: most probably https://github.com/mozilla/rust-android-gradle/issues/15: we're building arm when needing arm64 and then we use the old version of the megazord.

**Comment by vladikoff** [comment]
> we're building arm when needing arm64
