### ISSUE TITLE
RustSyncManager crashes with persistedState=null

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#1829]
A `null` persisted state is our "first sync" scenario.

```
                         E  Caused by: java.lang.NullPointerException
                         E      at mozilla.appservices.syncmanager.MsgTypes$SyncParams.setPersistedState(MsgTypes.java:776)
                         E      at mozilla.appservices.syncmanager.MsgTypes$SyncParams.access$1100(MsgTypes.java:499)
                         E      at mozilla.appservices.syncmanager.MsgTypes$SyncParams$Builder.setPersistedState(MsgTypes.java:1605)
                         E      at mozilla.appservices.syncmanager.SyncParams.toProtobuf$syncmanager_release(SyncParams.kt:144)
                         E      at mozilla.appservices.syncmanager.SyncManager.sync(SyncManager.kt:48)
                         E      at mozilla.components.service.fxa.sync.WorkManagerSyncWorker.doWork(WorkManagerSyncManager.kt:328)
                         E      at androidx.work.CoroutineWorker$startWork$1.invokeSuspend(CoroutineWorker.kt:66)
                         E      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                         E      at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
                         E      at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
                         E      at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
                         E      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-447)
┆Story Points: 1
┆Sprint: SYNC - 2019-10-11
┆Epic: [Q3 1.1] Sync Manager / CWTS

**Comment by grigoryk** [comment]
Passing in an empty string (instead of `null`) appears to make things work, but let's fix this regardless.
