### ISSUE TITLE
Hitting SQL_BUSY and ConnectionAlreadyOpen while running migrations

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#1965]
This is after running migration code right at the startup. It's the first time we hit the storage layer from Fenix.

```
10-10 17:29:30.076 16279 16312 D places_ffi: places_connection_new
10-10 17:29:30.077 16279 16312 D places_ffi: places_connection_new
10-10 17:29:30.084 16279 16312 D places_ffi: places_history_import_from_fennec
10-10 17:29:30.091 16214 16214 I zygote  : Deoptimizing java.lang.Object androidx.collection.SimpleArrayMap.put(java.lang.Object, java.lang.Object) due to JIT inline cache
10-10 17:29:30.109 16279 16312 E places::ffi: Database busy: Error { code: DatabaseBusy, extended_code: 5 } Some("database is locked")
10-10 17:29:30.110 16279 16312 E FennecMigration: Failed to migrate (HISTORY, 1)
10-10 17:29:30.110 16279 16312 E FennecMigration: mozilla.appservices.places.PlacesConnectionBusy: Error executing SQL: database is locked
10-10 17:29:30.110 16279 16312 E FennecMigration: 	at mozilla.appservices.places.RustError.intoException(RustError.kt:12)
10-10 17:29:30.110 16279 16312 E FennecMigration: 	at mozilla.appservices.places.PlacesApi.importVisitsFromFennec(PlacesConnection.kt:8)
10-10 17:29:30.110 16279 16312 E FennecMigration: 	at mozilla.components.browser.storage.sync.PlacesHistoryStorage.importFromFennec(PlacesHistoryStorage.kt:3)
10-10 17:29:30.110 16279 16312 E FennecMigration: 	at mozilla.components.support.migration.FennecMigration$runMigrationsAsync$1.invokeSuspend(FennecMigration.kt:28)
10-10 17:29:30.110 16279 16312 E FennecMigration: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
10-10 17:29:30.110 16279 16312 E FennecMigration: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
10-10 17:29:30.110 16279 16312 E FennecMigration: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
10-10 17:29:30.110 16279 16312 E FennecMigration: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10-10 17:29:30.110 16279 16312 E FennecMigration: 	at java.lang.Thread.run(Thread.java:764)
10-10 17:29:30.110 16279 16312 D FennecMigration: Migrating (BOOKMARKS, 1)
10-10 17:29:30.110 16279 16312 D places_ffi: places_connection_new
10-10 17:29:30.112 16279 16312 D places_ffi: places_bookmarks_import_from_fennec
10-10 17:29:30.112 16279 16312 E places::ffi: Unexpected error: ConnectionAlreadyOpen
10-10 17:29:30.113 16279 16312 E FennecMigration: Failed to migrate (BOOKMARKS, 1)
10-10 17:29:30.113 16279 16312 E FennecMigration: mozilla.appservices.places.PlacesException: A connection of this type is already open
10-10 17:29:30.113 16279 16312 E FennecMigration: 	at mozilla.appservices.places.RustError.intoException(RustError.kt:4)
10-10 17:29:30.113 16279 16312 E FennecMigration: 	at mozilla.appservices.places.PlacesApi.importBookmarksFromFennec(PlacesConnection.kt:8)
10-10 17:29:30.113 16279 16312 E FennecMigration: 	at mozilla.components.browser.storage.sync.PlacesBookmarksStorage.importFromFennec(PlacesBookmarksStorage.kt:3)
10-10 17:29:30.113 16279 16312 E FennecMigration: 	at mozilla.components.support.migration.FennecMigration$runMigrationsAsync$1.invokeSuspend(FennecMigration.kt:22)
10-10 17:29:30.113 16279 16312 E FennecMigration: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
10-10 17:29:30.113 16279 16312 E FennecMigration: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
10-10 17:29:30.113 16279 16312 E FennecMigration: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
10-10 17:29:30.113 16279 16312 E FennecMigration: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10-10 17:29:30.113 16279 16312 E FennecMigration: 	at java.lang.Thread.run(Thread.java:764)
```

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-59)
┆Epic: Fenix Migration

**Comment by grigoryk** [comment]
I figured out how I was triggering this state in Fenix - https://github.com/mozilla-mobile/android-components/pull/4693#issuecomment-544050611, yay!

Without thinking too hard about this, the latter stacktrace may still indicate some kind of a library issue? So I'll leave it to ya'll to close.

**Comment by mhammond** [comment]
ConnectionAlreadyOpen is certainly explained by multiple threads. SQLITE_BUSY also would be if both history and bookmarks migrations were running concurrently. Without more detail it's not clear there's any issue in app-services, and we haven't seen it since, so I think it's safe to just close this.
