### ISSUE TITLE
Logins and FxA Android Samples crash on Android 6.0

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#197]
The crash I saw was

`java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib64/libcrypto.so" needed or dlopened by "/system/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"`

The android component sample is missing libcrypto here: 

![](http://v14d.com/i/5b899dd627070.jpg)

The sample from `a-s` seems to have all the libraries but crashes for me:

![](http://v14d.com/i/5b899ee65998a.jpg)

It works in the x86 emulator though

**Comment by ncalexan** [comment]
It's my belief that Thom fixed this via #194.  @vladikoff can you verify?

**Comment by vladikoff** [comment]
> @vladikoff can you verify?

Partially works on Android 6, but not on 9.

**Comment by vladikoff** [comment]
Seems like to repro this we can use this configuration:

![](http://v14d.com/i/5b8ed1b0f0977.jpg)

The current version seems to work on Android 5, 7+, but not on 6.

**Comment by thomcc** [comment]
IIUC fxa client sample is also effected, right?

**Comment by thomcc** [comment]
This is *probably* an issue where patchelf and strip are interacting with each-other badly, but hard to say for sure.

**Comment by vladikoff** [comment]
> IIUC fxa client sample is also effected, right?

Yeap

**Comment by vladikoff** [comment]
Updated crash message is the following:

```
09-05 10:33:59.818 24688-24977/org.mozilla.logins_example E/AndroidRuntime: FATAL EXCEPTION: ForkJoinPool.commonPool-worker-2
    Process: org.mozilla.logins_example, PID: 24688
    Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
    java.lang.RuntimeException: Firefox Account functionality not available
        at mozilla.components.service.fxa.FxaClient$Companion$1.invoke(FxaClient.kt:30)
        at mozilla.components.service.fxa.FxaClient$Companion$1.invoke(FxaClient.kt:15)
        at java.lang.reflect.Proxy.invoke(Proxy.java:393)
        at $Proxy0.fxa_get_custom_config(Unknown Source)
        at mozilla.components.service.fxa.Config$Companion$custom$1.invoke(Config.kt:34)
        at mozilla.components.service.fxa.Config$Companion$custom$1.invoke(Config.kt:16)
        at mozilla.components.service.fxa.RustObject$Companion$safeAsync$1.doResume(RustObject.kt:62)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:162)
        at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:26)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1388)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:251)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:845)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1674)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1629)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: invalid ELF file "/data/app/org.mozilla.logins_example-1/lib/arm/libfxa_client.so" load segment[7]: p_offset (0x59a000) + p_filesz (0x12e8) ( = 0x59b2e8) past end of file (0x59b2e8)
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at mozilla.components.service.fxa.FxaClient$Companion.<clinit>(FxaClient.kt:21)
        at mozilla.components.service.fxa.FxaClient.<clinit>(FxaClient.kt)
        at mozilla.components.service.fxa.RustObject$Companion$safeAsync$1.doResume(RustObject.kt:60)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42) 
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:162) 
        at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:26) 
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1388) 
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:251) 
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:845) 
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1674) 
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1629) 
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108) 
```

` dlopen failed: invalid ELF file`

**Comment by ncalexan** [comment]
OK, this is much more difficult to address than expected.  First, it's a bug -- the range check is just wrong.  The bug was introduced in https://android.googlesource.com/platform/bionic/+/3f987f5b3eeb2e0e94c0d826429dfb418fce945f and corrected in https://android.googlesource.com/platform/bionic/+/93ce35434ca5af43a7449e289959543f0a2426fa.

#250 is still good -- we should do it rather than using `patchelf` -- but it's not enough to address our Android 6.0 problems.  I'm digging into workarounds now.
