### ISSUE TITLE
Fennec bookmarks migration: PlacesException: A connection of this type is already open

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2290]
https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/6712649

```
mozilla.appservices.places.PlacesException: A connection of this type is already open
    at mozilla.appservices.places.RustError.intoException(RustError.kt:4)
    at mozilla.appservices.places.PlacesApi.importBookmarksFromFennec(PlacesConnection.kt:13)
    at mozilla.components.browser.storage.sync.PlacesBookmarksStorage.importFromFennec(PlacesBookmarksStorage.kt:3)
    at mozilla.components.support.migration.FennecMigrator$runMigrationsAsync$1.invokeSuspend(FennecMigrator.kt:32)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)

mozilla.components.support.migration.FennecMigratorException$MigrateBookmarksException: mozilla.appservices.places.PlacesException: A connection of this type is already open
    at mozilla.components.support.migration.FennecMigrator$runMigrationsAsync$1.invokeSuspend(FennecMigrator.kt:36)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
```

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-454)
┆Story Points: 3
┆Epic: Fenix Migration

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

closing - this has not been reported since dec 11 2019.
