### ISSUE TITLE
Fennec history migration: PlacesConnectionBusy: Error executing SQL: database is locked

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2291]
https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/6714577

```
mozilla.appservices.places.PlacesConnectionBusy: Error executing SQL: database is locked
    at mozilla.appservices.places.RustError.intoException(RustError.kt:12)
    at mozilla.appservices.places.PlacesApi.importVisitsFromFennec(PlacesConnection.kt:8)
    at mozilla.components.browser.storage.sync.PlacesHistoryStorage.importFromFennec(PlacesHistoryStorage.kt:3)
    at mozilla.components.support.migration.FennecMigrator$runMigrationsAsync$1.invokeSuspend(FennecMigrator.kt:19)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)

mozilla.components.support.migration.FennecMigratorException$MigrateHistoryException: mozilla.appservices.places.PlacesConnectionBusy: Error executing SQL: database is locked
    at mozilla.components.support.migration.FennecMigrator$runMigrationsAsync$1.invokeSuspend(FennecMigrator.kt:22)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
```

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-453)
┆Story Points: 3
┆Epic: Fenix Migration

**Comment by rfk** [comment]
I don't know if we can tell whether this is the *old* database or the *new* database that is throwing an error, and perhaps it's worth trying to add a separate error case to distinguish them.

Is it at all possible that the old database in the Fennec profile is locked, e.g. from an unclean shutdown of the old version of the app?

/cc @grigoryk

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Closing, error not reported since end nov 2019.
