### ISSUE TITLE
InternalPanicmozilla.appservices.places.RustError in intoException fatal: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2309]
From https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6775662/?environment=fenixNightly:

```
mozilla.appservices.places.InternalPanic: called `Option::unwrap()` on a `None` value
    at mozilla.appservices.places.RustError.intoException(RustError.kt:14)
    at mozilla.appservices.places.PlacesReaderConnection.getBookmarksTree(PlacesConnection.kt:10)
    at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$getTree$2.invokeSuspend(PlacesBookmarksStorage.kt:3)
    at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$getTree$2.invoke(PlacesBookmarksStorage.kt)
    at io.reactivex.plugins.RxJavaPlugins.startUndispatchedOrReturn(RxJavaPlugins.java:2)
    at io.reactivex.plugins.RxJavaPlugins.withContext(RxJavaPlugins.java:9)
    at mozilla.components.browser.storage.sync.PlacesBookmarksStorage.getTree(PlacesBookmarksStorage.kt:1)
    at io.reactivex.plugins.RxJavaPlugins.getTree$default(RxJavaPlugins.java:1)
    at org.mozilla.fenix.library.bookmarks.edit.EditBookmarkFragment$onResume$1$1.invokeSuspend(EditBookmarkFragment.kt:6)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:47)
```

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-469)

**Comment by rfk** [comment]
This hasn't been seen in entry in the last 30 days, I'm going to close it out.
