### ISSUE TITLE
Sync integration tests are broken

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#2360]
```
integration-test-helper: Running command destroy with args
integration-test-helper:    rust-login-sql-test--3KRdR@restmail.net
integration-test-helper:    rust-login-sql-test--3KRdR
integration-test-helper:    https://stable.dev.lcip.org/auth/
integration-test-helper: Error: Got HTTP status 500 during request:
integration-test-helper:    Requesting https://stable.dev.lcip.org/auth/v1/account/destroy
integration-test-helper:    Body {
  url: 'https://stable.dev.lcip.org/auth/v1/account/destroy',
  status: 500,
  statusText: 'Internal Server Error',
  headers:
   Headers {
     _headers:
      { date: [Array],
        'content-type': [Array],
        'content-length': [Array],
        connection: [Array],
        server: [Array],
        timestamp: [Array],
        'access-control-allow-origin': [Array],
        'access-control-expose-headers': [Array],
        'strict-transport-security': [Array],
        'x-frame-options': [Array],
        'x-xss-protection': [Array],
        'x-download-options': [Array],
        'x-content-type-options': [Array],
        'cache-control': [Array] } },
  ok: false,
  body:
   PassThrough {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { head: [Object], tail: [Object], length: 1 },
        length: 361,
        pipes: null,
        pipesCount: 0,
        flowing: null,
        ended: true,
        endEmitted: false,
        reading: false,
        sync: false,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        paused: true,
        emitClose: true,
        autoDestroy: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     _events:
      [Object: null prototype] { prefinish: [Function: prefinish] },
     _eventsCount: 1,
     _maxListeners: undefined,
     _writableState:
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        emitClose: true,
        autoDestroy: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: false,
     allowHalfOpen: true,
     _transformState:
      { afterTransform: [Function: bound afterTransform],
        needTransform: false,
        transforming: false,
        writecb: null,
        writechunk: null,
        writeencoding: 'buffer' } },
  bodyUsed: false,
  size: 0,
  timeout: 0,
  _raw: [],
  _abort: false }
integration-test-helper:     Response body: {"code":500,"errno":203,"error":"Internal Server Error","message":"A backend service request failed.","info":"https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/api.md#response-format","service":"subhub","operation":"deleteCustomer","method":"DELETE","path":{"_expectedKeys":{"array":["uid"],"set":{}},"_template":"/v1/sub/customer/:uid"}}
integration-test-helper: Error: 
integration-test-helper:    Error: HTTP status 500 (Internal Server Error)
    at request (/home/circleci/project/testing/sync-test/helper/index.js:117:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Helper script exited with 1, it's stdout was:```

```

This makes me think of https://github.com/mozilla/fxa/issues/1740?

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-503)
┆Epic: important not urgent
┆Sprint: SYNC - end 2020-01-17

**Comment by vladikoff** [comment]
cc @jrgm 

see the 500s above ^

**Comment by jrgm** [comment]
> This makes me think of mozilla/fxa#1740?

Exactly.

2019-12-09T13:30:23.656750908Z {"Timestamp":1575898223656000000,"Logger":"fxa-auth-server","Type":"subhub.deleteCustomer.failed","Severity":2,"Pid":1,"EnvVersion":"2.0","Fields":{"uid":"e450f22dcd654784923b5338c297eefa","err":"Error: A backend service request failed."}}
