### ISSUE TITLE
Bookmarks migration error: Error executing SQL: Integer -1 out of range at index 1

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2374]
From [sentry](https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/6848497/?environment=fennecBeta):

```
mozilla.appservices.places.PlacesException: Error executing SQL: Integer -1 out of range at index 1
    at mozilla.appservices.places.RustError.intoException(RustError.kt:4)
    at mozilla.appservices.places.PlacesApi.importBookmarksFromFennec(PlacesConnection.kt:13)
    at mozilla.components.browser.storage.sync.PlacesBookmarksStorage.importFromFennec(PlacesBookmarksStorage.kt:3)
    at mozilla.components.support.migration.FennecMigrator$runMigrationsAsync$1.invokeSuspend(FennecMigrator.kt:32)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)

mozilla.components.support.migration.FennecMigratorException$MigrateBookmarksException: mozilla.appservices.places.PlacesException: Error executing SQL: Integer -1 out of range at index 1
    at mozilla.components.support.migration.FennecMigrator$runMigrationsAsync$1.invokeSuspend(FennecMigrator.kt:36)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
```

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-519)
┆Story Points: 5
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2020-01-17

**Comment by rfk** [comment]
/cc @grigoryk 

It would be really awesome to know what "phase" of the bookmarks migration this error occurred at, ref https://github.com/mozilla/application-services/issues/2297

**Comment by mhammond** [comment]
This error message comes from https://github.com/jgallagher/rusqlite/blob/master/src/error.rs#L208. So best I can tell, it's coming from somewhere where we are trying to select the 2nd result column into an unsigned integer. I guess it's possible it's either in our repo or maybe even in dogear?

For giggles I tried the following patch to the tests, but it didn't provoke it.

```
diff --git a/components/places/tests/fennec_bookmarks.rs b/components/places/tests/fennec_bookmarks.rs
index 6ce8b89..ccd264a 100644
--- a/components/places/tests/fennec_bookmarks.rs
+++ b/components/places/tests/fennec_bookmarks.rs
@@ -282,6 +282,15 @@ fn test_import() -> Result<()> {
     ];
     insert_bookmarks(&fennec_db, &bookmarks)?;

+    let mut stmt = fennec_db.prepare(&
+        "INSERT INTO bookmarks(_id, title, url, type, parent, position, keyword,
+                               description, tags, favicon_id, created, modified,
+                               guid, deleted, localVersion, syncVersion)
+            VALUES (-1, 'test title', 'http://example.com/invalid_type', -1, 5, -1, NULL, NULL, NULL,
+                    -1, -1, -1, 'invalid-guid', -1, -1, -1)"
+    )?;
+    stmt.execute(NO_PARAMS,)?;
+
     let places_api = PlacesApi::new(tmpdir.path().join("places.sqlite"))?;

     let pinned = places::import::import_fennec_bookmarks(&places_api, fennec_path)?;
```

It's probably worth investigating how to improve that so we get better "invalid data" coverage.
