### ISSUE TITLE
Logins migration error: The logins tables are not empty

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2375]
From [sentry](https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/6848498/?environment=fennecBeta):

```
mozilla.appservices.logins.LoginsStorageException: The logins tables are not empty
    at mozilla.appservices.logins.rust.RustError.intoException(RustError.kt:4)
    at mozilla.appservices.logins.DatabaseLoginsStorage.importLogins(DatabaseLoginsStorage.kt:12)
    at mozilla.components.service.sync.logins.AsyncLoginsStorageAdapter$importLoginsAsync$1.invokeSuspend(AsyncLoginsStorage.kt:6)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:47)
```

We throw this exception on purpose, so I wonder if it's an upstream bug in the Fenix migration code that is calling this on a non-empty logins table, perhaps re-trying a failed migration? /cc @grigoryk

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-520)
┆Story Points: 5
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2020-01-03

**Comment by grigoryk** [comment]
There are a few things here:
- we have some crashes that can happen and prevent us from persisting state of a migration (which will stop it from running again).
- I forgot to wrap the actual `import` call in try/catch, and so we get a crash loop.

Fixing this is on a-c (making sure throwing rust code doesn't crash the migration, and fixing other issues that lead up this situation). https://github.com/mozilla-mobile/android-components/issues/5346
