### ISSUE TITLE
Error: The application-services megazord has not yet been initialized

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#2449]
From Slack:  https://mozilla.slack.com/archives/CBBH6GU91/p1578497843001100
```
2020-01-08 10:34:20.639 12387-12387/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.reference.browser, PID: 12387
    java.lang.ExceptionInInitializerError
        at mozilla.appservices.httpconfig.LibViaduct.<clinit>(Unknown Source:0)
        at mozilla.appservices.httpconfig.RustHttpConfig.setClient(HttpConfig.kt:42)
        at mozilla.components.support.rusthttp.RustHttpConfig.setClient(RustHttpConfig.kt:25)
        at org.mozilla.reference.browser.BrowserApplication.onCreate(BrowserApplication.kt:27)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: mozilla.appservices.support.native.MegazordNotInitialized: The application-services megazord has not yet been initialized, but is needed by "viaduct"
        at mozilla.appservices.support.native.HelpersKt.lookupMegazordLibrary(Helpers.kt:108)
        at mozilla.appservices.support.native.HelpersKt.findMegazordLibraryName(Helpers.kt:142)
        at mozilla.appservices.httpconfig.LibViaduct$Companion$INSTANCE$1.invoke(LibViaduct.kt:41)
        at mozilla.appservices.httpconfig.LibViaduct$Companion$INSTANCE$1.invoke(LibViaduct.kt:15)
        at mozilla.appservices.httpconfig.LibViaduct$Companion.<clinit>(LibViaduct.kt:16)
        at mozilla.appservices.httpconfig.LibViaduct.<clinit>(Unknown Source:0) 
        at mozilla.appservices.httpconfig.RustHttpConfig.setClient(HttpConfig.kt:42) 
        at mozilla.components.support.rusthttp.RustHttpConfig.setClient(RustHttpConfig.kt:25) 
        at org.mozilla.reference.browser.BrowserApplication.onCreate(BrowserApplication.kt:27) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
```

reproduced locally: https://gist.githubusercontent.com/vladikoff/bf92351b6b83da0d80e55a58917642d2/raw/16052a93b7445dddc68963683f95d09df7bb6d9c/gistfile1.txt

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-575)

**Comment by vladikoff** [comment]
Reports are that this is only happening on ARM and not on x86 emulators. 

From Slack:
"I would guess https://github.com/mozilla/application-services/pull/2379 is related" ~ eoger
