### ISSUE TITLE
Fenix disconnected from FxA and can't sign back in

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2464]
My Fenix got disconnected from FxA, and when I try to sign back in it crashes.

In my logcat output I see:

```
01-13 17:51:42.874  6809  6866 D fxaclient_ffi: fxa_from_json
01-13 17:51:42.876  6809  6866 W fxa_client::ffi: Unexpected error: Error(
01-13 17:51:42.876  6809  6866 W fxa_client::ffi:
01-13 17:51:42.876  6809  6866 W fxa_client::ffi: JSON error: missing field `introspection_endpoint`)
01-13 17:51:42.877  6809  6809 D libglean_ffi: glean_ffi: Android logging should be hooked up!
01-13 17:51:42.877  6809  6866 E FirefoxAccountStateMachine: Failed to load saved account. Re-initializing...
01-13 17:51:42.877  6809  6866 E FirefoxAccountStateMachine: mozilla.appservices.fxaclient.FxaException$Unspecified: JSON error: missing field `introspection_endpoint`
01-13 17:51:42.877  6809  6866 E FirefoxAccountStateMachine:    at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:4)
01-13 17:51:42.877  6809  6866 E FirefoxAccountStateMachine:    at mozilla.appservices.fxaclient.FirefoxAccount$Companion.fromJSONString(FirefoxAccount.kt:6)
01-13 17:51:42.877  6809  6866 E FirefoxAccountStateMachine:    at mozilla.components.service.fxa.FirefoxAccount$Companion.fromJSONString(FirefoxAccount.kt:1)
01-13 17:51:42.877  6809  6866 E FirefoxAccountStateMachine:    at mozilla.components.service.fxa.SecureAbove22AccountStorage.read(AccountStorage.kt:6)
01-13 17:51:42.877  6809  6866 E FirefoxAccountStateMachine:    at mozilla.components.service.fxa.manager.FxaAccountManager.stateActions(FxaAccountManager.kt:219)
01-13 17:51:42.877  6809  6866 E FirefoxAccountStateMachine:    at mozilla.components.service.fxa.manager.FxaAccountManager$processQueueAsync$1.invokeSuspend(FxaAccountManager.kt:27)
01-13 17:51:42.877  6809  6866 E FirefoxAccountStateMachine:    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
01-13 17:51:42.877  6809  6866 E FirefoxAccountStateMachine:    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
01-13 17:51:42.877  6809  6866 E FirefoxAccountStateMachine:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-13 17:51:42.877  6809  6866 E FirefoxAccountStateMachine:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-13 17:51:42.877  6809  6866 E FirefoxAccountStateMachine:    at java.lang.Thread.run(Thread.java:764)
01-13 17:51:42.877  6809  6866 I FirefoxAccountStateMachine: Ran 'Event$Init' side-effects for state Start, got successive event Event$AccountNotFound
01-13 17:51:42.878  6809  6866 I FirefoxAccountStateMachine: Processing event Event$AccountNotFound for state Start. Next state is NotAuthenticated
```

Which makes me think this may be related to https://github.com/mozilla/application-services/pull/2321, perhaps we needed to add a migration to existing serialized config info to handle the new field.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-587)

**Comment by rfk** [comment]
It looks like #2321 was first released in v0.45 in early December. However, android-components was never updated to this version, it was on v0.44 until very recently when we updated all the way to v0.48.1.

**Comment by rfk** [comment]
This might explain the [spurt of `MissingExpectedAccountAfterStartup` errors](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6629522/?query=is:unresolved) seen recently in senty; /cc @grigoryk.

**Comment by rfk** [comment]
On the plus side, I appear to be getting this error every time I launch Fenix, so its alleged attempt to transition me to the `NotAuthenticated` state isn't working, and maybe it's still got my login credentials as part of the serialized state...

**Comment by rfk** [comment]
I have a basic fix in https://github.com/mozilla/application-services/pull/2465, we should try to get this into a dot-release ASAP so that Fenix has the choice of either rolling forward to fix or rolling back.

**Comment by rfk** [comment]
For completeness: I manually QAed this by:

* Making a build of Fenix that used a-s 0.44, installing it and signing in.
* Making a build of latest Fenix master (using a-s 0.48.1), updating to it, and confirming that this reproduced the bug reported here (Fenix claimed I was signed out).
* Making a build of latest Fenix master using a-s 0.48.2, and updating to it.

After the last update, Fenix was able to deserialize my existing account state and continue happily syncing.
