### ISSUE TITLE
Cannot migrate from a sessionToken that already has a device record

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2473]
As seen in https://github.com/mozilla-mobile/android-components/issues/5551, the current Fennec -> Fenix migration process can fail with a "Session already registered by another device" when it tries to take over the sessionToken (and corresponding device record) owned by Fennec.

I think there's a decent workaround for Fenix in the short term, but we need to figure out why this is and what to do about it so that we can bring back a more polished account migration experience.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-593)
┆Story Points: 3
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2020-01-17

**Comment by rfk** [comment]
Well, at least it's easy to reproduce:

```
>>> s = fxa.core.Client().login("ryan-three@rfk.id.au", getpass.getpass())
Password: 
>>> s.apiclient.post("/account/device", {"name": "foo", "type": "desktop" }, auth=s._auth)
{u'pushEndpointExpired': False, u'availableCommands': {}, u'type': u'desktop', u'id': u'26ab583223666afa7eec0b49daaabe7a', u'createdAt': 1578987426713, u'name': u'foo'}
>>> s.apiclient.post("/oauth/token", {"client_id": "a2270f727f45f648", "scope": "profile https://identity.mozilla.com/apps/oldsync", "access_type": "offline"}, auth=s._auth)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rfk/.opt/venvs/moz/local/lib/python2.7/site-packages/PyFxA-0.7.2-py2.7.egg/fxa/_utils.py", line 335, in post
    return self.request("POST", url, json, **kwds)
  File "/home/rfk/.opt/venvs/moz/local/lib/python2.7/site-packages/PyFxA-0.7.2-py2.7.egg/fxa/_utils.py", line 321, in request
    raise fxa.errors.ClientError(body)
fxa.errors.ClientError: Session already registered by another device
>>>
```

I think this is a bug in the fxa-auth-server, the logic [here](https://github.com/mozilla/fxa/blob/455176a34d1638cdfd4e3c490f749b7065b48eb5/packages/fxa-auth-server/lib/routes/utils/oauth.js#L48) for creating a placeholder device record doesn't work correctly if the originating sessionToken already has a device record.
