### ISSUE TITLE
FxA throws errors on push messages it can't handle

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/application-services#2710]
Original: https://github.com/mozilla-mobile/android-components/issues/5662

```
2020-01-21 13:40:26.117 32199-32395/org.mozilla.reference.browser.debug E/FxaDeviceConstellation: Error while running: processing raw events
    mozilla.appservices.fxaclient.FxaException$Unspecified: JSON error: expected value at line 1 column 1
        at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:48)
        at mozilla.appservices.fxaclient.FirefoxAccount.handlePushMessage(FirefoxAccount.kt:895)
        at mozilla.components.service.fxa.FxaDeviceConstellation$processRawEventAsync$1$1.invoke(FxaDeviceConstellation.kt:69)
        at mozilla.components.service.fxa.FxaDeviceConstellation$processRawEventAsync$1$1.invoke(FxaDeviceConstellation.kt:33)
        at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invokeSuspend(Utils.kt:68)
        at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invoke(Unknown Source:10)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:28)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:60)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:67)
        at mozilla.components.service.fxa.FxaDeviceConstellation$processRawEventAsync$1.invokeSuspend(FxaDeviceConstellation.kt:68)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
```

It doesn't break functionality, but it would be nicer if FxA didn't throw those errors on messages it can't handle, but rather gracefully log them instead.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-872)

**Comment by jonalmeida** [comment]
Closing as duplicate.

**Comment by eoger** [comment]
If you can reproduce reliably, would you mind logging what gets sent to `handlePushMessage`?

**Comment by jonalmeida** [comment]
> If you can reproduce reliably, would you mind logging what gets sent to `handlePushMessage`?

@eoger decrypted WebPush messages were going to FxA since it was observing all incoming messages at the time. It might be safe to close this since we're now [filtering out non-FxA push messages](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/FxaPushSupportFeature.kt#L179).

To answer your question though, it was a decrypted message from the [WebPush data encryption test page](https://mozilla-services.github.io/WebPushDataTestPage/) (: `This is test data.\n`

**Comment by eoger** [comment]
Right this makes sense, the filtering should solve this problem, it's actually a good thing that we'll throw on these errors now.
