### ISSUE TITLE
Possible viaduct failure due to java threading issue

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2757]
From https://github.com/MozillaReality/FirefoxReality/issues/2924#issuecomment-595142429; see this traceback:

```
2020-03-05 11:04:47.189 2582-2716/org.mozilla.vrbrowser.dev E/FxaDeviceConstellation: Error while running: ensuring capabilities mozilla.appservices.fxaclient.FxaException$Network: Network error: Network error: Java error: "Expected thread 1 (\"main\"), but running on thread 175 (\"DefaultDispatcher-worker-2\")" at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:43) at mozilla.appservices.fxaclient.FirefoxAccount.ensureCapabilities(FirefoxAccount.kt:919) at mozilla.components.service.fxa.FxaDeviceConstellation$ensureCapabilitiesAsync$1$1.invoke(FxaDeviceConstellation.kt:61) at mozilla.components.service.fxa.FxaDeviceConstellation$ensureCapabilitiesAsync$1$1.invoke(FxaDeviceConstellation.kt:33) at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invokeSuspend(Utils.kt:68) at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invoke(Utils.kt) at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:28) at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:60) at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:67) at mozilla.components.service.fxa.FxaDeviceConstellation$ensureCapabilitiesAsync$1.invokeSuspend(FxaDeviceConstellation.kt:60) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655) 2020-03-05 11:04:47.190 2582-2694/org.mozilla.vrbrowser.dev W/FirefoxAccountStateMachine: Failed to ensure device capabilities. Stopping.
```

This reads like a java-threading-related error was thrown while rust code was making a network call, which I don't think we ever expect to happen?

**Comment by thomcc** [comment]
Yikes, that seems nasty. No, we don't expect this to ever happen -- I wonder if they're calling network stuff on the main thread, and we're calling it back off main thread? I have to re-learn how this works.

That said, Viaduct (unlike logging) doesn't do any threading stuff, that happens entirely on the geckoview side.
