### ISSUE TITLE
Can't run a-s related united tests in a-c from Android Studio

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#2952]
Some (not all, IIRC) unit tests in a-c which touch real a-s do not currently work in Android Studio, but work fine in CLI and in our CI.

All failures are of this shape:
```
java.lang.NoSuchMethodError: mozilla.appservices.places.MsgTypes$HistoryVisitInfos.emptyProtobufList()Lcom/google/protobuf/Internal$ProtobufList;

	at mozilla.appservices.places.MsgTypes$HistoryVisitInfos.<init>(MsgTypes.java:900)
	at mozilla.appservices.places.MsgTypes$HistoryVisitInfos.<clinit>(MsgTypes.java:1326)
	at mozilla.appservices.places.PlacesReaderConnection.getVisitInfos(PlacesConnection.kt:339)
	at mozilla.components.browser.storage.sync.PlacesHistoryStorage$getDetailedVisits$2.invokeSuspend(PlacesHistoryStorage.kt:90)
	at |b|b|b(Coroutine boundary.|b(|b)
	at mozilla.components.browser.storage.sync.PlacesHistoryStorageTest$history import v34 populated$1.invokeSuspend(PlacesHistoryStorageTest.kt:785)
Caused by: java.lang.NoSuchMethodError: mozilla.appservices.places.MsgTypes$HistoryVisitInfos.emptyProtobufList()Lcom/google/protobuf/Internal$ProtobufList;
	at mozilla.appservices.places.MsgTypes$HistoryVisitInfos.<init>(MsgTypes.java:900)
	at mozilla.appservices.places.MsgTypes$HistoryVisitInfos.<clinit>(MsgTypes.java:1326)
	at mozilla.appservices.places.PlacesReaderConnection.getVisitInfos(PlacesConnection.kt:339)
	at mozilla.components.browser.storage.sync.PlacesHistoryStorage$getDetailedVisits$2.invokeSuspend(PlacesHistoryStorage.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1103)
┆Sprint: Backlog

**Comment by eoger** [comment]
From what I got on Google, it seems like the class was compiled with a different version of the protobuf library than the one at runtime. (we did upgrade the lib recently). I'd suggest clearing the Android Studio gradle cache?

**Comment by grigoryk** [comment]
Leaving breadcrumbs:
- https://github.com/google/tink/issues/282
- https://github.com/robolectric/robolectric/issues/2643
- https://github.com/robolectric/robolectric/pull/5547
