### ISSUE TITLE
Android networking appears broken in v0.58 release

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#3032]
Ref https://github.com/mozilla-mobile/android-components/pull/6636#issuecomment-618711216

```
04-23 15:37:47.745 15466 15524 E viaduct::backend::ffi: Viaduct Ffi Error: doFetch failed: null
04-23 15:37:47.746 15466 15524 E viaduct::backend::ffi: Missing HTTP status
04-23 15:37:47.746 15466 15524 W fxa_client::ffi: Network error: Error(
04-23 15:37:47.746 15466 15524 W fxa_client::ffi:
04-23 15:37:47.746 15466 15524 W fxa_client::ffi: Network error: Backend error: Missing HTTP status)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: Error while running: complete oauth flow
04-23 15:37:47.746 15466 15524 E FirefoxAccount: mozilla.appservices.fxaclient.FxaException$Network: Network error: Backend error: Missing HTTP status
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:43)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.appservices.fxaclient.FirefoxAccount.completeOAuthFlow(FirefoxAccount.kt:687)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.FirefoxAccount$completeOAuthFlowAsync$1$1.invoke(FirefoxAccount.kt:196)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.FirefoxAccount$completeOAuthFlowAsync$1$1.invoke(FirefoxAccount.kt:29)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invokeSuspend(Utils.kt:68)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invoke(Unknown Source:10)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:28)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:60)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:67)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at mozilla.components.service.fxa.FirefoxAccount$completeOAuthFlowAsync$1.invokeSuspend(FirefoxAccount.kt:195)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
04-23 15:37:47.746 15466 15524 E FirefoxAccount: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

From slack, @eoger suggested that this might be caused by an compatibility between the Kotlin-side and Rust-side protobuf libraries, and aligning their version numbers could be a good place to start.

I'll also note that I couldn't find any tests for the Kotlin side of viaduct in our repo. As part of resolving this, I wonder what it would look like to try to make a minimal mock `concept-fetch` client on the Kotlin side, call it through the FFI layer, and confirm that it produces the expected result.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1170)
┆Sprint: SYNC - end 2020-05-08

**Comment by rfk** [comment]
> I'll also note that I couldn't find any tests for the Kotlin side of viaduct in our repo. As part of 
> resolving this, I wonder what it would look like to try to make a minimal mock concept-fetch client
> on the Kotlin side, call it through the FFI layer, and confirm that it produces the expected result.

I filed https://github.com/mozilla/application-services/issues/3060 to continue this thread.
