### ISSUE TITLE
Taskcluster failing to upload android symbols

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#3244]
CI for the [v61.0.0 release](https://github.com/mozilla/application-services/commit/3b8203e66ad5918e5eb4aa43740f8c62c0b419e1) failed with [this error](https://firefox-ci-tc.services.mozilla.com/tasks/BfEWVxQyRdyI-9RDjSBgBg/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FBfEWVxQyRdyI-9RDjSBgBg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log) about being unable to generate android symbols:

```
Unexpected error: [Errno 2] No such file or directory: '/build/android-sdk/ndk//toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-objcopy': '/build/android-sdk/ndk//toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-objcopy'
Traceback (most recent call last):
  File "automation/symbols-generation/symbolstore.py", line 738, in <module>
    main()
  File "automation/symbols-generation/symbolstore.py", line 734, in main
    dumper.Process(args[2])
  File "automation/symbols-generation/symbolstore.py", line 368, in Process
    self.ProcessFile(file_to_process)
  File "automation/symbols-generation/symbolstore.py", line 380, in ProcessFile
    self.ProcessFileWork(file, arch_num, arch, None, dsymbundle)
  File "automation/symbols-generation/symbolstore.py", line 467, in ProcessFileWork
    code_file, code_id)
  File "automation/symbols-generation/symbolstore.py", line 600, in CopyDebug
    if subprocess.call([self.objcopy, '--only-keep-debug', file, file_dbg]) == 0 and \
  File "/usr/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/build/android-sdk/ndk//toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-objcopy': '/build/android-sdk/ndk//toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-objcopy'
```

This comes from the `./automation/upload_android_symbols.sh` script, which uses various environment variables to try to find the paths for things in the android NDK. From slack conversation we think they may be interactind bacly with the [recent change to use side-by-side NDK)[https://github.com/mozilla/application-services/pull/3222}, since that PR talks about removing the need for the `$ANDROID_NDK_ROOT` environment variable, but the script still tries to use it.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1400)
┆Sprint: Backlog

**Comment by rfk** [comment]
Theory: we need to take the same logic as we use locally for [setting `ANDROID_NDK_HOME` from the ndkVersion](https://github.com/mozilla/application-services/pull/3222/files#r439115090) when building libs, and apply it in the taskcluster dockerfile, since #3222 removed the older logic for setting those vars in that docker image.

**Comment by rfk** [comment]
Not quite, but close. It turns out that `upload_android_symbols.sh` tries to get `$ANDROID_NDK_HOME` by sourcing `./libs/android_defaults.sh`, which tries to read the sdk version number by running `./gradlew  -q printNdkVersion | tail -1`. But that must be failing in this case, returning an empty string, and resulting in `$ANDROID_NDK_HOME=/build/android-sdk/ndk//` with the double slash where the ndk version is supposed to be.

**Comment by rfk** [comment]
Yep, [earlier in the log](https://firefox-ci-tc.services.mozilla.com/tasks/BfEWVxQyRdyI-9RDjSBgBg/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FBfEWVxQyRdyI-9RDjSBgBg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L1539) we see:

```
NDK_VERSION=$(./gradlew -q printNdkVersion | tail -1)
+++ ./gradlew -q printNdkVersion
+++ tail -1
libs/android_defaults.sh: line 5: ./gradlew: No such file or directory
```
