### ISSUE TITLE
[Push] push::crypto - base64 failed for target:dh; InvalidLength

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/application-services#3364]
We're seeing a large portion of these errors being reported and it's unclear to me what the cause is as we're passing the message from FCM to the native layer where it fails.

If this is expected behaviour, maybe this shouldn't be forwarded to the crash reporter?

```
mozilla.components.support.rustlog.RustErrorException: push::crypto - base64 failed for target:dh; InvalidLength
    at mozilla.components.support.rustlog.CrashReporterOnLog.invoke(RustLog.kt:11)
    at mozilla.appservices.rustlog.RawLogCallbackImpl.invoke(RustLogAdapter.kt:3)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:11)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:1)
    at com.sun.jna.Native.invokePointer(Native.java)
    at com.sun.jna.Function.invokePointer(Function.java:1)
    at com.sun.jna.Function.invoke(Function.java:60)
    at com.sun.jna.Function.invoke(Function.java:22)
    at com.sun.jna.Library$Handler.invoke(Library.java:27)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy5.push_decrypt
    at mozilla.appservices.push.PushManager.decrypt(PushManager.kt:5)
    at mozilla.components.feature.push.RustPushConnection.decryptMessage(Connection.kt:5)
    at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$$inlined$ifInitialized$lambda$1.invokeSuspend(AutoPushFeature.kt:12)
    at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$$inlined$ifInitialized$lambda$1.invoke
    at mozilla.components.feature.push.ext.CoroutineScopeKt$launchAndTry$2.invokeSuspend(CoroutineScope.kt:5)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
```

Sentry links:
 - https://sentry.prod.mozaws.net/operations/fenix/issues/8820595/
 - https://sentry.prod.mozaws.net/operations/fenix/issues/8820593/
 - https://sentry.prod.mozaws.net/operations/fenix/issues/8836387/
 - https://sentry.prod.mozaws.net/operations/fenix/issues/8865107/

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1492)
┆Sprint: Backlog

**Comment by jonalmeida** [comment]
cc: @jrconlin

**Comment by jrconlin** [comment]
These appear to start around Jun 30. There was no change to the push servers at that time. Do we know if the body is empty for these? If so, that may cause the error we're seeing.

**Comment by jonalmeida** [comment]
@jrconlin these showed up recently because we started to forward the errors to the crash reporter which we were not doing before.

**Comment by rfk** [comment]
I managed to reproduce this exact error message by attempting to decode a `dh` value surrounded by double-quotes, like `dh=\"BMOebOMWSRisAhWpRK9ZPszJC8BL9MiWvLZBoBU6pG6Kh6vUFSW4BHFMh0b83xCg3_7IgfQZXwmVuyu27vwiv5c\"`. I have high confidence that the issue here is the same as #3365, it's just manifesting differently because the quoted string has an invalid length, and thus the base64-decoder bails out before it even tries to decode the first (invalid) character.

**Comment by jdragojevic** [comment]
@jonalmeida  - the sentry errors referenced in this issue appear to have stopped with the push server deploy yesterday afternoon.  I'll leave this for you to close.
