### ISSUE TITLE
crash at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:5)

### ISSUE THREAD

**Issue by keianhzo** [mozilla/application-services#3387]
We are getting some of this in FxR after the latest v11 release with AC v44:

mozilla.appservices.fxaclient.FxaException$Network
	at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:5)
	at mozilla.appservices.fxaclient.FirefoxAccount.getTokenServerEndpointURL(FirefoxAccount.kt:9)
	at mozilla.components.service.fxa.manager.FxaAccountManager.maybeUpdateSyncAuthInfoCache(FxaAccountManager.kt:17)
	at mozilla.components.service.fxa.manager.FxaAccountManager$maybeUpdateSyncAuthInfoCache$1.invokeSuspend(FxaAccountManager.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

┆Issue is synchronized with this Jira Task
┆Epic: a-s consumer issues
┆Sprint: Backlog

**Comment by thomcc** [comment]
Unless I'm misunderstanding, this is just a network error -- You probably want to catch and ignore these, and retry later or report it to the user somehow.

**Comment by rfk** [comment]
@grigoryk I recall seeing a similar error recently on android-components, but can't find it in my awesome bar - does this look like a possible dupe to something in a-c?

**Comment by keianhzo** [comment]
This has become our top crasher for v11

**Comment by mhammond** [comment]
> This has become our top crasher for v11. Anything we can do to help debug this?

Best I can tell, app-services is just treating this as a regular, catchable exception. I had a quick look but couldn't find your repo - where is your code calling this?

**Comment by keianhzo** [comment]
We call it through Android Components so if it's their responsibility to catch that maybe I move the issue there.

**Comment by keianhzo** [comment]
Moved to AC https://github.com/MozillaReality/FirefoxReality/issues/3733
