### ISSUE TITLE
Ensure push subscription endpoints are nullable or verify as non-null

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/application-services#3737]
@mhammond mentioned that desktop would sometimes not receive an endpoint in the subscription and something that we should check that we do as well.

In the Android Component, we expect a non-null value from the rust component, so if we did receive one, we would report that to Sentry (at this time, I don't see anything that sticks out with missing endpoints in Sentry).

We should check that missing values are not passed to us from the rust component as empty strings instead.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2579)
┆Epic: Important backlog

**Comment by jonalmeida** [comment]
Hmm.. we do have this one that is classified as a CommunicationError in the rust component: https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/7567960

```
mozilla.appservices.push.CommunicationServerError: Error(

Communication Server Error: "Could not fetch endpoint: Backend error: Missing HTTP status")
    at mozilla.appservices.push.RustError.intoException(RustError.kt:12)
    at mozilla.appservices.push.PushManager.subscribe(PushManager.kt:13)
    at mozilla.components.feature.push.RustPushConnection.subscribe(Connection.kt:4)
    at mozilla.components.feature.push.AutoPushFeature$subscribe$3$2.invokeSuspend(AutoPushFeature.kt:5)
    at mozilla.components.feature.push.AutoPushFeature$subscribe$3$2.invoke
    at mozilla.components.feature.push.AutoPushFeatureKt$launchAndTry$1.invokeSuspend(AutoPushFeature.kt:5)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:19)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)

mozilla.components.concept.push.PushError$Rust: Error(

Communication Server Error: "Could not fetch endpoint: Backend error: Missing HTTP status")
    at mozilla.components.feature.push.AutoPushFeature$launchAndTry$2.invoke(AutoPushFeature.kt:3)
    at mozilla.components.feature.push.AutoPushFeatureKt$launchAndTry$1.invokeSuspend(AutoPushFeature.kt:17)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:19)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
```

**Comment by jonalmeida** [comment]
We should probably uncouple this from communication error since those are regarded as intermittent network failures and are not reported to Sentry.

Follow-up: figure out where the "retry" on failure should go?

**Comment by jonalmeida** [comment]
> We should check that missing values are not passed to us from the rust component as empty strings instead.

This seems to be fine in the rust code since the endpoint is a [non-null string](https://github.com/mozilla/application-services/blob/main/components/push/src/communications.rs#L42). In a case prior, it was the nullable value `appServerKey` which would always come back as a non-null empty string.

> We should probably uncouple this from communication error since those are regarded as intermittent network failures and are not reported to Sentry.

Using this ticket in that case to make a separate error for this case so we can catch it on the application side.

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866332

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
