### ISSUE TITLE
Autofill store fails to initialize due to missing trigger

### ISSUE THREAD

**Issue by csadilek** [mozilla/application-services#4106]
We're seeing some early user reports of crashes after the latest A-S upgrade (76.0.0). The crashes happen when initializing  `mozilla.appservices.autofill.Store` which fails due to a missing trigger (`credit_cards_tombstones_afterinsert_trigger`).

Note that I cannot reproduce this. Wondering if this may be caused by a failed DB migration?

Sentry query: 
https://sentry.prod.mozaws.net/operations/firefox-nightly/?query=is%3Aunresolved+credit_cards_tombstones_afterinsert_trigger

https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/11334539/

Fenix ticket: https://github.com/mozilla-mobile/fenix/issues/19508

```
mozilla.appservices.autofill.SqlError: Error executing SQL: no such trigger: credit_cards_tombstones_afterinsert_trigger
    at mozilla.appservices.autofill.Error.intoException(autofill.kt:14)
    at mozilla.appservices.autofill.Store.<init>(autofill.kt:7)
    at mozilla.components.service.sync.autofill.AutofillStorageConnection.init$service_sync_autofill_release(AutofillCreditCardsAddressesStorage.kt:3)
    at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage$conn$2.invoke(AutofillCreditCardsAddressesStorage.kt:1)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
    at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage.getConn
    at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage.access$getConn$p(AutofillCreditCardsAddressesStorage.kt:1)
    at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage$getAllCreditCards$2.invokeSuspend(AutofillCreditCardsAddressesStorage.kt:2)
    at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage$getAllCreditCards$2.invoke(AutofillCreditCardsAddressesStorage.kt:2)
    at androidx.core.app.AppOpsManagerCompat.startUndispatchedOrReturn(AppOpsManagerCompat.java:2)
    at kotlinx.coroutines.AwaitKt.withContext(Await.kt:9)
    at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage.getAllCreditCards(AutofillCreditCardsAddressesStorage.kt:1)
    at mozilla.components.service.sync.autofill.GeckoCreditCardsAddressesStorageDelegate$onCreditCardsFetch$1.invokeSuspend(GeckoCreditCardsAddressesStorageDelegate.kt:5)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2209)
┆Sprint: Backlog

**Comment by bendk** [comment]
The migration code drops the credit cards table, then assumes that the triggers will be recreated by the `create()` function.  If there's an error in the migration code, then I don't think `create()` will run and that trigger will be missing.

It seems like there's a general question here: what do we do if the migration fails?  If that happens, we can't really assume anything about the state of the DB, so do we have to delete the DB and start from scratch?
