### ISSUE TITLE
CircleCI "Rust tests - beta" job failing due to missing rustfmt

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#4108]
The "Run tests - beta" job in CircleCI has [been failing](https://app.circleci.com/pipelines/github/mozilla/application-services/26835/workflows/5f7cde5c-018d-425c-b0b0-b8cc783d5435/jobs/103047) lately, apparently due to a failure to find `rustfmt` for the beta Rust toolchain:

```
#!/bin/bash -eo pipefail
RUSTUP_TOOLCHAIN="beta" automation/tests.py rust-tests

platform: uname_result(system='Linux', node='0ea0819e4dd6', release='4.15.0-1092-aws', version='#98-Ubuntu SMP Wed Jan 6 22:22:51 UTC 2021', machine='x86_64', processor='')
info: syncing channel updates for 'beta-x86_64-unknown-linux-gnu'
info: latest update on 2021-05-08, rust version 1.53.0-beta.2 (4bac69dd2 2021-05-07)
info: downloading component 'cargo'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: installing component 'cargo'
info: using up to 500.0 MiB of RAM to unpack components
info: installing component 'rust-std'
info: installing component 'rustc'
rustc version: rustc 1.53.0-beta.2 (4bac69dd2 2021-05-07)
cargo version: cargo 1.53.0-beta (4369396ce 2021-04-27)
error: 'rustfmt' is not installed for the toolchain 'beta-x86_64-unknown-linux-gnu'
To install, run `rustup component add rustfmt --toolchain beta-x86_64-unknown-linux-gnu`
Traceback (most recent call last):
  File "automation/tests.py", line 406, in <module>
    main()
  File "automation/tests.py", line 393, in main
    for step in calc_steps(args):
  File "automation/tests.py", line 321, in calc_steps
    print_rust_environment()
  File "automation/tests.py", line 208, in print_rust_environment
    print('rustfmt version: {}'.format(get_output(['rustfmt', '--version'])))
  File "automation/tests.py", line 61, in get_output
    output = subprocess.check_output(cmdline, **kwargs).decode('utf8')
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['rustfmt', '--version']' returned non-zero exit status 1.

Exited with code exit status 1

CircleCI received exit code 1
```

I don't really understand why this is happening, or what might have changed to trigger it.

What I believe is *supposed* to happen is that rustup reads our `rust-toolchain` file, sees that we specify `components = ["clippy", "rustfmt"]`, and automatically installs those components into the requested toolchain. Indeed, if I try to run the same `RUSTUP_TOOLCHAIN="beta" automation/tests.py rust-tests` command locally, it automagically installs `rustfmt` for me and the command runs to completion.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2210)
┆Sprint: Backlog

**Comment by rfk** [comment]
> What I believe is supposed to happen is that rustup reads our rust-toolchain file, sees that we specify
> components = ["clippy", "rustfmt"], and automatically installs those components into the requested toolchain.

From some local experimentation, my expectations here are not correct - specifying `RUSTUP_TOOLCHAIN=beta` causes it to ignore our `rust-toolchain` file, and rustup will instead install the default set of components for the currently active [profile](https://rust-lang.github.io/rustup/concepts/profiles.html). Perhaps CI is defaulting to the "minimal" profile, which does not include `rustfmt` by default?

**Comment by rfk** [comment]
> Perhaps CI is defaulting to the "minimal" profile, which does not include rustfmt by default?

Indeed, this is exactly what's happening:

```
[rfk] ~ % docker run circleci/rust:latest cat /usr/local/rustup/settings.toml
default_host_triple = "x86_64-unknown-linux-gnu"
default_toolchain = "1.51.0-x86_64-unknown-linux-gnu"
profile = "minimal"
version = "12"

[overrides]
```

**Comment by rfk** [comment]
We *could* fix this by explicitly installing `rustfmt`, or by explicitly calling `rustup set profile default`, but I think it will be better long-term to move to the newer CircleCI rust docker image which seems to use the default profile by default; ref https://github.com/mozilla/application-services/pull/4110
