### ISSUE TITLE
Error executing SQL: CHECK constraint failed: credit_cards_data when editing CC in Fenix

### ISSUE THREAD

**Issue by codrut-topliceanu** [mozilla/application-services#4119]
We have a crash when trying to edit a credit over in Fenix. Seems to originate from `mozilla.appservices.autofill.Store`. 
I don't think we can solve it in Fenix without further info, could you provide some assistance please?

See https://github.com/mozilla-mobile/fenix/issues/19492 for STR.

```kotlin
c8dbb688-7eed-4c4e-b92f-34f9b11d3c7b
mozilla.appservices.autofill.ErrorException$SqlError: Error executing SQL: CHECK constraint failed: credit_cards_data
----
mozilla.appservices.autofill.ErrorException$SqlError: Error executing SQL: CHECK constraint failed: credit_cards_data
at mozilla.appservices.autofill.Error.intoException(autofill.kt:14)
at mozilla.appservices.autofill.Store.updateCreditCard(autofill.kt:6)
at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage$updateCreditCard$2.invokeSuspend(AutofillCreditCardsAddressesStorage.kt:25)
at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage$updateCreditCard$2.invoke(AutofillCreditCardsAddressesStorage.kt:2)
at androidx.core.app.AppOpsManagerCompat.startUndispatchedOrReturn(AppOpsManagerCompat.java:2)
at kotlinx.coroutines.AwaitKt.withContext(Await.kt:9)
at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage.updateCreditCard(AutofillCreditCardsAddressesStorage.kt:1)
at org.mozilla.fenix.settings.creditcards.controller.DefaultCreditCardEditorController$handleUpdateCreditCard$1.invokeSuspend(CreditCardEditorController.kt:5)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2214)
┆Epic: a-s storage components (backlog)
┆Sprint: SYNC - 2021-05-28

**Comment by mhammond** [comment]
FTR, I commented in that fenix issue that (a) I can't repro and (b) I suspect an early version of app-services - possibly pre encryption

**Comment by codrut-topliceanu** [comment]
Issue no longer relevant.
