### ISSUE TITLE
NullPointerExceptionorg.mozilla.experiments.nimbus.internal.NimbusClient in fetchExperiments

### ISSUE THREAD

**Issue by kbrosnan** [mozilla/application-services#4380]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.concurrent.atomic.AtomicLong.decrementAndGet()' on a null object reference
    at org.mozilla.experiments.nimbus.internal.NimbusClient.fetchExperiments(nimbus.kt:16)
    at org.mozilla.experiments.nimbus.Nimbus$fetchExperimentsOnThisThread$1.invoke(Nimbus.kt:1)
    at org.mozilla.experiments.nimbus.Nimbus.withCatchAll(Nimbus.kt:1)
    at org.mozilla.experiments.nimbus.Nimbus.fetchExperimentsOnThisThread$nimbus_release(Nimbus.kt:1)
    at org.mozilla.experiments.nimbus.Nimbus$fetchExperiments$1.invokeSuspend(Nimbus.kt:2)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
```

Fenix crash in v91 on devices running Android 5.1 and 5.1.1 https://sentry.prod.mozaws.net/operations/firefox/issues/12245085/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2726)
┆Sprint End Date: 2021-08-20

**Comment by data-sync-user** [comment]
➤ Tarik Eshaq commented:

Dropping this to the backlog, for now, we can re-prioritize it later if Fenix prioritizes older android versions or if this happens to other android versions.

**Comment by mhammond** [comment]
This doesn't seem actionable at the moment.
