### ISSUE TITLE
BufferOverflowExceptionjava.nio.Buffer in checkPutBounds

### ISSUE THREAD

**Issue by kbrosnan** [mozilla/application-services#4381]
```
java.nio.BufferOverflowException: null
    at java.nio.Buffer.checkPutBounds(Buffer.java:183)
    at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:356)
    at java.nio.ByteBuffer.put(ByteBuffer.java:721)
    at org.mozilla.experiments.nimbus.internal.NimbusKt.lower(nimbus.kt:3)
    at org.mozilla.experiments.nimbus.internal.NimbusClient.<init>(nimbus.kt:4)
    at org.mozilla.experiments.nimbus.Nimbus.<init>(Nimbus.kt:17)
    at mozilla.components.service.nimbus.Nimbus.<init>(Nimbus.kt:28)
    at mozilla.components.service.nimbus.Nimbus.<init>(Nimbus.kt:2)
    at org.mozilla.fenix.experiments.NimbusSetupKt.createNimbus(NimbusSetup.kt:9)
    at org.mozilla.fenix.components.Analytics$experiments$2.invoke(Analytics.kt:1)
    at org.mozilla.fenix.perf.LazyMonitored$lazyValue$1.invoke(LazyMonitored.kt:2)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
    at org.mozilla.fenix.perf.LazyMonitored.getValue(LazyMonitored.kt:1)
    at org.mozilla.fenix.components.Analytics.getExperiments(Analytics.kt)
    at org.mozilla.fenix.FenixApplication$setupMegazord$1.invokeSuspend(FenixApplication.kt:7)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```
Fenix crash in v91 on devices running Android 6.0 and 6.0.1 https://sentry.prod.mozaws.net/operations/firefox/issues/12234439/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2727)
┆Sprint End Date: 2021-08-20

**Comment by rfk** [comment]
>     at org.mozilla.experiments.nimbus.internal.NimbusKt.lower(nimbus.kt:3)

(Wanted to leave a couple of clues for further investigation)

This is almost certainly a bug in or around the UniFFI-generated bindings for lowering something across the FFI, rather than anything Nimbus is doing. It's unexpected, because we do a lot of work to ensure that we have a correctly-sized buffer, see e.g. the `reserve` helper method:

* https://github.com/mozilla/uniffi-rs/blob/5790b646526b204a7afc9a2ffbe961ce40174a36/uniffi_bindgen/src/bindings/kotlin/templates/RustBufferTemplate.kt#L90

Interesting that it seems to be on a specific Android version and I wonder if there may be known issues or limitations with `nio.DirectByteBuffer` on those versions?

Alternately, I know we've had some issues in the past with the way JNA caches values between the JVM-level representation
of a struct and the flat bytes in memory that it uses to talk to C code. For example, when we want to resize a buffer we have to explicitly "flush" the new length into the underlying C struct using `writeField` her:

* https://github.com/mozilla/uniffi-rs/blob/5790b646526b204a7afc9a2ffbe961ce40174a36/uniffi_bindgen/src/bindings/kotlin/templates/RustBufferTemplate.kt#L97

I wonder if there's the possibility of a caching issue around the `capacity` field that could lead us to under-allocate the buffer?

**Comment by mhammond** [comment]
> Interesting that it seems to be on a specific Android version

Yeah - an old android, but the problem only started 7 days ago. How can we determine what app-services version was used for v91? That should help us identify the uniffi version and maybe pinpoint a change we made?

**Comment by kbrosnan** [comment]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/11941076/ shows it starting in Beta on July 21st. No data on nightly, looks like no one with affected phones is running nightly https://sentry.prod.mozaws.net/operations/firefox-nightly/?query=is%3Aunresolved+java.nio.Buffer+in+checkPutBounds

**Comment by data-sync-user** [comment]
➤ Tarik Eshaq commented:

Dropping this to the backlog, for now, we can re-prioritize it later if Fenix prioritizes older android versions or if this happens to other android versions

**Comment by mhammond** [comment]
Not actionable at the moment.
