### ISSUE TITLE
org.mozilla.experiments.nimbus.internal.NimbusErrorException$InternalError: Internal error: New experiment but enrollment already exists.

### ISSUE THREAD

**Issue by kbrosnan** [mozilla/application-services#4382]
```
org.mozilla.experiments.nimbus.internal.NimbusErrorException$InternalError: Internal error: New experiment but enrollment already exists.
    at org.mozilla.experiments.nimbus.internal.NimbusError.intoException(nimbus.kt:9)
    at org.mozilla.experiments.nimbus.internal.NimbusClient.applyPendingExperiments(nimbus.kt:15)
    at org.mozilla.experiments.nimbus.-$$LambdaGroup$ks$FFGd6J-jWuYuF4BxN9FoSzJwXkw.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:4)
    at org.mozilla.experiments.nimbus.Nimbus.withCatchAll(Nimbus.kt:1)
    at org.mozilla.experiments.nimbus.Nimbus.applyPendingExperimentsOnThisThread$nimbus_release(Nimbus.kt:1)
    at org.mozilla.experiments.nimbus.Nimbus$applyPendingExperiments$1.invokeSuspend(Nimbus.kt:2)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:923)
```
Fenix crash https://sentry.prod.mozaws.net/operations/firefox/issues/12219507/ Nothing specific about the OS version or devices that are crashing. Looks to be a random sample of our users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2729)

**Comment by tarikeshaq** [comment]
This seems to be a Nimbus-specific problem, tracking that here: https://mozilla-hub.atlassian.net/browse/SDK-358
