### ISSUE TITLE
RustErrorExceptionmozilla.components.support.rustlog.CrashReporterOnLog in invoke logins::error - Invalid login: Login already exists

### ISSUE THREAD

**Issue by kbrosnan** [mozilla/application-services#4383]
```
mozilla.components.support.rustlog.RustErrorException: logins::error - Invalid login: Login already exists
    at mozilla.components.support.rustlog.CrashReporterOnLog.invoke(RustLog.kt:9)
    at mozilla.appservices.rustlog.RawLogCallbackImpl.invoke(RustLogAdapter.kt:3)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:11)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:1)
    at com.sun.jna.Native.invokeVoid(Native.java)
    at com.sun.jna.Function.invoke(Function.java:98)
    at com.sun.jna.Function.invoke(Function.java:22)
    at com.sun.jna.Library$Handler.invoke(Library.java:31)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy13.logins_6ab5_LoginStore_check_valid_with_no_dupes
    at mozilla.appservices.logins.LoginStore.checkValidWithNoDupes(logins.kt:5)
    at mozilla.appservices.logins.DatabaseLoginsStorage.ensureValid(DatabaseLoginsStorage.kt:3)
    at mozilla.components.service.sync.logins.SyncableLoginsStorage$ensureValid$2.invokeSuspend(SyncableLoginsStorage.kt:2)
    at mozilla.components.service.sync.logins.SyncableLoginsStorage$ensureValid$2.invoke(SyncableLoginsStorage.kt:2)
    at androidx.core.app.AppOpsManagerCompat.startUndispatchedOrReturn(AppOpsManagerCompat.java:2)
    at kotlinx.coroutines.AwaitKt.withContext(Await.kt:9)
    at mozilla.components.service.sync.logins.SyncableLoginsStorage.ensureValid(SyncableLoginsStorage.kt:1)
    at mozilla.components.service.sync.logins.DefaultLoginValidationDelegate$ensureValidAsync$1.invokeSuspend(DefaultLoginValidationDelegate.kt:12)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```
Crash in Fenix 91 https://sentry.prod.mozaws.net/operations/firefox/issues/12252022/ Nothing specific about the OS version or devices that are crashing. Looks to be a random sample of our users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2728)

**Comment by skhamis** [comment]
This seems to be the same error/duplicate of https://sentry.prod.mozaws.net/share/issue/748c25f4bc734de0beb10c0b83fee4bf/

**Comment by kbrosnan** [comment]
Lets close this then as it does not sound useful.
