### ISSUE TITLE
mozilla.appservices.logins.LoginsStorageException$InvalidKey: at mozilla.appservices.logins.LoginsStorageException$ErrorHandler.read(logins.kt:5)

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla/application-services#4505]
mozilla.appservices.logins.LoginsStorageException$InvalidKey
	at mozilla.appservices.logins.LoginsStorageException$ErrorHandler.read(logins.kt:5)
	at mozilla.appservices.logins.LoginsStorageException$ErrorHandler$lift$1.invoke(logins.kt:2)
	at mozilla.appservices.logins.LoginsStorageException$ErrorHandler$lift$1.invoke(logins.kt:1)
	at mozilla.appservices.logins.LoginsKt.liftFromRustBuffer(logins.kt:2)
	at mozilla.appservices.logins.LoginsStorageException$ErrorHandler.lift(logins.kt:2)
	at mozilla.appservices.logins.LoginsStorageException$ErrorHandler.lift(logins.kt:1)
	at mozilla.appservices.logins.LoginStore.<init>(logins.kt:13)
	at mozilla.appservices.logins.DatabaseLoginsStorage.unlock(DatabaseLoginsStorage.kt:3)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage$conn$2.invoke(SyncableLoginsStorage.kt:9)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:5)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage.getConn(SyncableLoginsStorage.kt:1)
	at 

mozilla.components.service.sync.logins.SyncableLoginsStorage$warmUp$2.invokeSuspend(SyncableLoginsStorage.kt:6)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage$warmUp$2.invoke(SyncableLoginsStorage.kt:2)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:9)
	at 

org.mozilla.fenix.FenixApplication$initVisualCompletenessQueueAndQueueTasks$queueInitStorageAndServices$1$1.invokeSuspend(FenixApplication.kt:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

Crash in Fenix 94. https://crash-stats.mozilla.org/report/index/08a2e8a8-4c20-4880-8aab-fca170210927. https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/12273657/?query=is%3Aunresolved%20InvalidKey

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2802)

**Comment by bendk** [comment]
I don't think we've changed the logins code recently, so I don't think this is a regression.  If I had to take a guess, I would maybe say that it's database corruption.  In any case, I don't think we need to address this at this point.

**Comment by bendk** [comment]
I just saw this error while testing the sqlcipher upgrade, then trying to go back to the current nightly code.  I'm pretty sure the issue for me was that the SQLCipher key was deleted as part of the migration process, and I think that this will happen in general whenever we lose that key or if it gets corrupted somehow.

This should be addressed by the new logins API, which uses a canary to detect this and recover.  Unfortunately the best we can do for recovery is to delete all the local data and restart, but this is better than crashing.
