### ISSUE TITLE
SQLCipher migration error

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#4528]
I'm seeing this error when trying to run the sqlcipher migration on android:

```
10-05 11:00:39.606 28562 28602 D logins  : logins_5236_migrate_logins
10-05 11:00:39.607 28562 28602 W logins::schema: user_version: 0
10-05 11:00:39.607 28562 28602 D logins::schema: Creating schema
10-05 11:00:39.700 28562 28602 I logins::migrate_sqlcipher_db: Imported pUy0LfdwMTED successfully.
10-05 11:00:39.700 28562 28602 I logins::migrate_sqlcipher_db: Imported {7bd822e1-5b81-45ed-8496-e2b8ed65ab61} successfully.
10-05 11:00:39.700 28562 28602 I logins::migrate_sqlcipher_db: Imported {3086cd3c-3655-45fc-b8bf-1f01d3604231} successfully.
10-05 11:00:39.700 28562 28602 I logins::migrate_sqlcipher_db: Imported {c9f23f50-e0dd-46bd-b0b0-80c460305820} successfully.
10-05 11:00:39.700 28562 28602 I logins::migrate_sqlcipher_db: Imported {ba2cf853-6e56-4863-8cb9-f33897c59f67} successfully.
10-05 11:00:39.700 28562 28602 I logins::migrate_sqlcipher_db: Imported hNdTSKVCMTx8 successfully.
10-05 11:00:39.700 28562 28602 I logins::migrate_sqlcipher_db: Imported Kr9rxmVX4RmD successfully.
10-05 11:00:39.700 28562 28602 I logins::migrate_sqlcipher_db: Imported -11uohRTLpxn successfully.
10-05 11:00:39.701 28562 28602 I logins::migrate_sqlcipher_db: Imported bZivJO5FVQx3 successfully.
10-05 11:00:39.701 28562 28602 I logins::migrate_sqlcipher_db: Imported {77f64e5f-e4e7-4774-b3f9-c2ee78c1936e} successfully.
10-05 11:00:39.701 28562 28602 I logins::migrate_sqlcipher_db: Imported {53fa2b31-7865-497e-bdef-c60f11344e45} successfully.
10-05 11:00:39.705 28562 28602 I logins::migrate_sqlcipher_db: Finished importing logins with the following metrics: MigrationMetrics {
10-05 11:00:39.705 28562 28602 I logins::migrate_sqlcipher_db:     fixup_phase: MigrationPhaseMetrics {
10-05 11:00:39.705 28562 28602 I logins::migrate_sqlcipher_db:         num_processed: 0,
10-05 11:00:39.705 28562 28602 I logins::migrate_sqlcipher_db:         num_succeeded: 0,
10-05 11:00:39.705 28562 28602 I logins::migrate_sqlcipher_db:         num_failed: 0,
10-05 11:00:39.705 28562 28602 I logins::migrate_sqlcipher_db:         total_duration: 0,
10-05 11:00:39.705 28562 28602 I logins::migrate_sqlcipher_db:         errors: [],
10-05 11:00:39.705 28562 28602 I logins::migrate_sqlcipher_db:     },
10-05 11:00:39.705 28562 28602 I logins::migrate_sqlcipher_db:     insert_phase: MigrationPhaseMetrics {
10-05 11:00:39.705 28562 28602 I logins::migrate_sqlcipher_db:         num_processed: 0,
10-05 11:00:39.705 28562 28602 I logins::migrate_sqlcipher_db:         num_succeeded: 0,
10-05 11:00:39.705 28562 28602 I logins::migrate_sqlcipher_db:         num_failed: 0,
10-05 11:00:39.705 28562 28602 I logins::migrate_sqlcipher_db:         total_duration: 0,
10-05 11:00:39.705 28562 28602 I logins::migrate_sqlcipher_db:         errors: [],
10-05 11:00:39.705 28562 28602 I logins::migrate_sqlcipher_db:     },
10-05 11:00:39.705 28562 28602 I logins::migrate_sqlcipher_db:     num_processed: 11,
10-05 11:00:39.705 28562 28602 I logins::migrate_sqlcipher_db:     num_succeeded: 11,
10-05 11:00:39.705 28562 28602 I logins::migrate_sqlcipher_db:     num_failed: 0,
10-05 11:00:39.705 28562 28602 I logins::migrate_sqlcipher_db:     total_duration: 5,
10-05 11:00:39.705 28562 28602 I logins::migrate_sqlcipher_db:     errors: [],
10-05 11:00:39.705 28562 28602 I logins::migrate_sqlcipher_db: }
10-05 11:00:39.707 28562 28602 I logins::migrate_sqlcipher_db: Imported global_sync_id successfully
10-05 11:00:39.709 28562 28602 I logins::migrate_sqlcipher_db: Imported passwords_sync_id successfully
10-05 11:00:39.710 28562 28602 I mozac/CrashReporter: Caught Exception report submitted to 1 services
10-05 11:00:39.711 28562 28602 E logins::error: UnexpectedLoginsStorageError error: SqlError(InvalidColumnType(1, "value", Integer))
10-05 11:00:39.735  1422  1457 I PeriodicStatsRunner: PeriodicStatsRunner.call():180 call()
10-05 11:00:39.735  1422  1457 I PeriodicStatsRunner: PeriodicStatsRunner.call():184 No submit PeriodicStats since input started.
10-05 11:00:39.766 28562 28602 E ExceptionHandler: Uncaught exception handled: 
10-05 11:00:39.766 28562 28602 E ExceptionHandler: mozilla.appservices.logins.LoginsStorageException$UnexpectedLoginsStorageException: Unexpected error: SqlError
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at mozilla.appservices.logins.LoginsStorageException$ErrorHandler.read(logins.kt:899)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at mozilla.appservices.logins.LoginsStorageException$ErrorHandler$lift$1.invoke(logins.kt:893)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at mozilla.appservices.logins.LoginsStorageException$ErrorHandler$lift$1.invoke(logins.kt:893)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at mozilla.appservices.logins.LoginsKt.liftFromRustBuffer(logins.kt:182)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at mozilla.appservices.logins.LoginsStorageException$ErrorHandler.lift(logins.kt:893)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at mozilla.appservices.logins.LoginsStorageException$ErrorHandler.lift(logins.kt:891)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at mozilla.appservices.logins.LoginsKt.migrateLogins(logins.kt:1652)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at mozilla.components.service.sync.logins.SyncableLoginsStorage.migrateSQLCipherDBIfNeeded(SyncableLoginsStorage.kt:284)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at mozilla.components.service.sync.logins.SyncableLoginsStorage.access$migrateSQLCipherDBIfNeeded(SyncableLoginsStorage.kt:107)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at mozilla.components.service.sync.logins.SyncableLoginsStorage$conn$2.invoke(SyncableLoginsStorage.kt:115)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at mozilla.components.service.sync.logins.SyncableLoginsStorage$conn$2.invoke(SyncableLoginsStorage.kt:114)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at mozilla.components.service.sync.logins.SyncableLoginsStorage.getConn(SyncableLoginsStorage.kt:114)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at mozilla.components.service.sync.logins.SyncableLoginsStorage.access$getConn(SyncableLoginsStorage.kt:107)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at mozilla.components.service.sync.logins.SyncableLoginsStorage$warmUp$2.invokeSuspend(SyncableLoginsStorage.kt:124)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at mozilla.components.service.sync.logins.SyncableLoginsStorage$warmUp$2.invoke(Unknown Source:8)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at mozilla.components.service.sync.logins.SyncableLoginsStorage$warmUp$2.invoke(Unknown Source:4)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at mozilla.components.service.sync.logins.SyncableLoginsStorage.warmUp(SyncableLoginsStorage.kt:123)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at org.mozilla.fenix.FenixApplication$initVisualCompletenessQueueAndQueueTasks$queueInitStorageAndServices$1$1.invokeSuspend(FenixApplication.kt:245)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
10-05 11:00:39.766 28562 28602 E ExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2810)
┆Epic: Logins update and sqlcipher migration
┆Sprint End Date: 2021-10-15

**Comment by bendk** [comment]
I think that second issue is also fixed.  At least I'm not getting crashes anymore.
