### ISSUE TITLE
NPE in places.kt - lowerIntoRustBuffer

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#4532]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/13490638/

Crash happens in the uniffi-generated `places.kt`, in the `catch` branch within `lowerIntoRustBuffer`.

Looks like `bbuf` is null here, so probably `buf.finalize()` throws an NPE and then the error handler further tries to access `bbuf` and crashes.

```
java.lang.NullPointerException: null
    at mozilla.appservices.places.uniffi.RustBufferBuilder.finalize(places.kt:2)
    at mozilla.appservices.places.uniffi.RustBufferBuilder.discard(places.kt:1)
    at mozilla.appservices.places.uniffi.PlacesKt.lowerIntoRustBuffer(places.kt:4)
    at mozilla.appservices.places.uniffi.HistoryMetadataObservation.lower$places_release(places.kt:1)
    at mozilla.appservices.places.uniffi.PlacesKt.placesNoteHistoryMetadataObservation(places.kt:3)
    at mozilla.appservices.places.PlacesWriterConnection.noteHistoryMetadataObservation(PlacesConnection.kt:4)
    at mozilla.components.browser.storage.sync.PlacesHistoryStorage$noteHistoryMetadataObservation$2.invokeSuspend(PlacesHistoryStorage.kt:5)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2812)
┆Epic: [2021] Completed unparented
┆Sprint End Date: 2021-10-29

**Comment by bendk** [comment]
I think this is more of a UniFFI issue, so let's use that one to track this.
