### ISSUE TITLE
LoginsKt.lower: NullPointerException

### ISSUE THREAD

**Issue by pocmo** [mozilla/application-services#4640]
From Fenix 95.0 Beta 1 and 2:

```
java.lang.NullPointerException: null
    at mozilla.appservices.logins.LoginsKt.lower(logins.kt:3)
    at mozilla.appservices.logins.LoginsKt.checkCanary(logins.kt:3)
    at mozilla.components.service.sync.logins.LoginsCrypto.getManagedKey(LoginsCrypto.kt:5)
    at mozilla.components.service.sync.logins.LoginsCrypto.key(LoginsCrypto.kt:2)
    at mozilla.components.service.sync.logins.SyncableLoginsStorage$getByBaseDomain$2.invokeSuspend(SyncableLoginsStorage.kt:2)
    at mozilla.components.service.sync.logins.SyncableLoginsStorage$getByBaseDomain$2.invoke(SyncableLoginsStorage.kt:2)
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
    at kotlinx.coroutines.BuildersKt.withContext
    at mozilla.components.service.sync.logins.SyncableLoginsStorage.getByBaseDomain(SyncableLoginsStorage.kt:1)
    at mozilla.components.service.sync.logins.GeckoLoginStorageDelegate$onLoginFetch$1.invokeSuspend(GeckoLoginStorageDelegate.kt:6)
```

Sentry: https://sentry.prod.mozaws.net/operations/firefox-beta/issues/14791360/
A-C: https://github.com/mozilla-mobile/android-components/issues/11250

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/SYNC-2886)
┆Epic: Logins update and sqlcipher migration
┆Sprint End Date: 2021-11-24

**Comment by bendk** [comment]
This one is really weird.  My current guess is that somehow `RustBuffer.alloc()` is returning a `RustBuffer` where data is `null`.  I'm not sure how that could happen, maybe it's related to an odd size value (0, negative, very large).  I made a uniffi PR to that adds a check for this.  I'm thinking that we can try to push that one through and see if we catch anything with it.

**Comment by bendk** [comment]
More reports from crash-stats.  It seems like this one may be happening on startup?

https://crash-stats.mozilla.org/signature/?product=Fenix&version=95.2.0&signature=java.lang.NullPointerException%3A%20at%20mozilla.appservices.logins.LoginsKt.lower%28logins.kt%3A3%29&date=%3E%3D2021-12-14T17%3A57%3A00.000Z&date=%3C2021-12-21T17%3A57%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1#summary
