### ISSUE TITLE
DatabaseLoginsStorage.addOrUpdate: InvalidRecord: InvalidLogin::DuplicateLogin

### ISSUE THREAD

**Issue by pocmo** [mozilla/application-services#4641]
From Fenix 95.0 Beta 1 and 2:

```
mozilla.appservices.logins.InvalidRecord: InvalidLogin::DuplicateLogin
    at mozilla.appservices.logins.LoginsStorageException$ErrorHandler.read(logins.kt:7)
    at mozilla.appservices.logins.LoginsStorageException$ErrorHandler$lift$1.invoke(logins.kt:2)
    at mozilla.appservices.logins.LoginsStorageException$ErrorHandler$lift$1.invoke(logins.kt:1)
    at mozilla.appservices.logins.LoginsKt.liftFromRustBuffer(logins.kt:2)
    at mozilla.appservices.logins.LoginsStorageException$ErrorHandler.lift(logins.kt:2)
    at mozilla.appservices.logins.LoginsStorageException$ErrorHandler.lift(logins.kt:1)
    at mozilla.appservices.logins.LoginStore.addOrUpdate(logins.kt:17)
    at mozilla.appservices.logins.DatabaseLoginsStorage.addOrUpdate(DatabaseLoginsStorage.kt:3)
    at mozilla.components.service.sync.logins.SyncableLoginsStorage$addOrUpdate$2.invokeSuspend(SyncableLoginsStorage.kt:6)
    at mozilla.components.service.sync.logins.SyncableLoginsStorage$addOrUpdate$2.invoke(SyncableLoginsStorage.kt:2)
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
    at kotlinx.coroutines.BuildersKt.withContext
    at mozilla.components.service.sync.logins.SyncableLoginsStorage.addOrUpdate(SyncableLoginsStorage.kt:1)
    at mozilla.components.service.sync.logins.GeckoLoginStorageDelegate$onLoginSave$1.invokeSuspend(GeckoLoginStorageDelegate.kt:6
````

Sentry: https://sentry.prod.mozaws.net/operations/firefox-beta/issues/14655345/
A-C: https://github.com/mozilla-mobile/android-components/issues/11251

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/SYNC-2885)
┆Epic: Logins update and sqlcipher migration
┆Sprint End Date: 2021-11-24

**Comment by pocmo** [comment]
Closing in favor of #4648.
