### ISSUE TITLE
LoginStore.getByBaseDomain: (mozilla.appservices.logins.InternalException: called `Result::unwrap()` on an `Err` value: PoisonError 

### ISSUE THREAD

**Issue by pocmo** [mozilla/application-services#4658]
This cash jumped up to rank 5 in crash stats. But overall volume is still low. However it looks like we do not handle this error correctly and maybe that's easy to fix.

```
mozilla.appservices.logins.InternalException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
    at mozilla.appservices.logins.LoginStore.getByBaseDomain(logins.kt:14)
    at mozilla.appservices.logins.DatabaseLoginsStorage.getByBaseDomain(DatabaseLoginsStorage.kt:3)
    at mozilla.components.service.sync.logins.SyncableLoginsStorage$getByBaseDomain$2.invokeSuspend(SyncableLoginsStorage.kt:5)
    at mozilla.components.service.sync.logins.SyncableLoginsStorage$getByBaseDomain$2.invoke(SyncableLoginsStorage.kt:2)
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
    at kotlinx.coroutines.BuildersKt.withContext
    at mozilla.components.service.sync.logins.SyncableLoginsStorage.getByBaseDomain(SyncableLoginsStorage.kt:1)
    at mozilla.components.service.sync.logins.GeckoLoginStorageDelegate$onLoginFetch$1.invokeSuspend(GeckoLoginStorageDelegate.kt:6)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
````

Sentry: https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/14011601/
Fenix: https://github.com/mozilla-mobile/fenix/issues/22443

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2900)
┆sprintEndDate: 2021-11-24

**Comment by bendk** [comment]
I think we can close this one and use #4661 to track the poison errors in general.  Also, the #4663 PR should fix this.
