### ISSUE TITLE
Perma-failure with Push Communication Error: "response has no uaid" 

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/application-services#4691]
Web Push seems to be perma failing on Firefox Nightly. The failure cannot be seen in Sentry since it's wrapped as a `CommunicationException` which is [not considered a fatal error](https://github.com/mozilla-mobile/android-components/blob/68458f02c2e9da3abf9aad96730719938df218ad/components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt#L363-L380).

In this case, I think it would be a higher priority since all push messages for web apps are not working. We're going to be cutting a new release soon so this bug will make it's way into a larger audience soon (beta).

Example stack trace:
```
2021-12-01 10:57:40.449 5405-5468/? I/push::internal::communications: subscribed to channel '76c38b6bc53539a581a0f94657220c81' via "https://updates.push.services.mozilla.com/v1/fcm/boxwood-axon-825/registration/8fb95819733748f28a13e9ab7b0206c0/subscription" - 200
2021-12-01 10:57:40.451 5405-5468/? E/WebPushEngineDelegate: Error on push onSubscribe.
2021-12-01 10:57:40.453 5405-5468/? W/App: Non-fatal error occurred in AutoPushFeature.
    mozilla.appservices.push.PushException$CommunicationException: Communication Error: "response has no `uaid`"
        at mozilla.appservices.push.PushException$ErrorHandler.read(push.kt:15)
        at mozilla.appservices.push.PushException$ErrorHandler$lift$1.invoke(push.kt:2)
        at mozilla.appservices.push.PushException$ErrorHandler$lift$1.invoke(push.kt:1)
        at mozilla.appservices.push.PushKt.liftFromRustBuffer(push.kt:2)
        at mozilla.appservices.push.PushException$ErrorHandler.lift(push.kt:2)
        at mozilla.appservices.push.PushException$ErrorHandler.lift(push.kt:1)
        at mozilla.appservices.push.PushManager.subscribe(push.kt:17)
        at mozilla.components.feature.push.RustPushConnection.subscribe(Connection.kt:4)
        at mozilla.components.feature.push.AutoPushFeature$subscribe$3$2.invokeSuspend(AutoPushFeature.kt:4)
        at mozilla.components.feature.push.AutoPushFeature$subscribe$3$2.invoke(AutoPushFeature.kt:2)
        at mozilla.components.feature.push.ext.CoroutineScopeKt$launchAndTry$2.invokeSuspend(CoroutineScope.kt:4
```

Fenix tracking issues: https://github.com/mozilla-mobile/fenix/issues/22394

Device info: 
```
96.0a1 (Build #2015848875), 9fa9ae337+
AC: 96.0.20211130143618, 395aa21e64
GV: 96.0a1-20211130093553
AS: 86.2.0
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2927)
┆Story Points: 3
┆epic: Fix Push
┆sprintEndDate: 2021-12-10

**Comment by tarikeshaq** [comment]
From the url in the logs, it seems like this is happening when the client already knows the `uaid`, most likely on a new subscription, and not the first one.

I have a patch that I'll push up, that would use the `uaid` the client knows, when it doesn't get one from the server. It seems to me that the assumption that the server always returns the `uaid` is only change in semantics related to this that the recent work on push introduced.

we might want to verify our assumptions about what the server returns after we get this patched

**Comment by tarikeshaq** [comment]
The bug is fixed in AS, I'll cut a release that has the fix - I'll reopen this bug to track the release until we get it into AC

**Comment by tarikeshaq** [comment]
Closing this issue since the fix now landed in android components and no more work is expected on the application services side
