### ISSUE TITLE
Failing to sync - get_registered_sync_engine: database is locked

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#4791]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/17285798/events/d92467ed062e4fe9a397b7d2497121fe/

Perhaps fallout from https://github.com/mozilla/application-services/pull/4770, perhaps we already had this type of a thing already and this is just a new path to hit it?

```
mozilla.components.support.rustlog.RustErrorException: places::api::places_api - get_registered_sync_engine: Error opening database: Error executing SQL: database is locked
    at mozilla.components.support.rustlog.CrashReporterOnLog.invoke(RustLog.kt:9)
    at mozilla.appservices.rustlog.RawLogCallbackImpl.invoke(RustLogAdapter.kt:3)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:11)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:1)
    at com.sun.jna.Native.invokeStructure(Native.java)
    at com.sun.jna.Native.invokeStructure(Native.java:3)
    at com.sun.jna.Function.invoke(Function.java:65)
    at com.sun.jna.Function.invoke(Function.java:22)
    at com.sun.jna.Library$Handler.invoke(Library.java:32)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy16.syncmanager_47f4_SyncManager_sync
    at mozilla.appservices.syncmanager.SyncManager.sync(syncmanager.kt:6)
    at mozilla.components.service.fxa.sync.WorkManagerSyncWorker.access$doSync(WorkManagerSyncManager.kt:122)
    at mozilla.components.service.fxa.sync.WorkManagerSyncWorker$doWork$2.invokeSuspend(WorkManagerSyncManager.kt:42)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3028)

**Comment by grigoryk** [comment]
Yup, this isn't new - see https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/16148411/?query=is%3Aunresolved%20get_registered_sync_engine for the pre-uniffi version of this.

**Comment by grigoryk** [comment]
More context in https://github.com/mozilla/application-services/issues/4762 and https://github.com/mozilla/application-services/issues/4783
