### ISSUE TITLE
Crash in [@ mozilla.appservices.places.uniffi.PlacesException$InternalPanic: at mozilla.appservices.places.uniffi.FfiConverterTypePlacesError.read(places.kt:3)]

### ISSUE THREAD

**Issue by rvandermeulen** [mozilla/application-services#4990]
This is spiking in the Fenix 101 release, though it's been around since 99.

Crash report: https://crash-stats.mozilla.org/report/index/e928dc36-0a62-48f8-95de-1e98b0220607

Java stack trace:
```
mozilla.appservices.places.uniffi.PlacesException$InternalPanic
	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesError.read(places.kt:3)
	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesError$lift$1.invoke(places.kt:2)
	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesError$lift$1.invoke(places.kt:1)
	at mozilla.appservices.places.uniffi.PlacesKt.liftFromRustBuffer(places.kt:2)
	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesError.lift(places.kt:1)
	at mozilla.appservices.places.uniffi.PlacesException$ErrorHandler.lift(places.kt:2)
	at mozilla.appservices.places.uniffi.PlacesException$ErrorHandler.lift(places.kt:1)
	at mozilla.appservices.places.uniffi.PlacesConnection.getTopFrecentSiteInfos(places.kt:17)
	at mozilla.appservices.places.PlacesReaderConnection.getTopFrecentSiteInfos(PlacesConnection.kt:1)
	at mozilla.components.browser.storage.sync.PlacesHistoryStorage$getTopFrecentSites$2.invokeSuspend(PlacesHistoryStorage.kt:7)
	at mozilla.components.browser.storage.sync.PlacesHistoryStorage$getTopFrecentSites$2.invoke(PlacesHistoryStorage.kt:2)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:9)
	at mozilla.components.feature.top.sites.DefaultTopSitesStorage.getTopSites(DefaultTopSitesStorage.kt:26)
	at org.mozilla.fenix.FenixApplication$initVisualCompletenessQueueAndQueueTasks$queueInitStorageAndServices$1$1.invokeSuspend(FenixApplication.kt:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3198)
┆Story Points: 3
┆sprintEndDate: 2022-06-24

**Comment by tarikeshaq** [comment]
FWIW, `InternalPanic` is very misleading, as it's not a panic at all... [I've already renamed it to `InternalError`](https://github.com/mozilla/application-services/pull/4941) and it should be called that in the first firefox that used AS 93.1.0

**Comment by tarikeshaq** [comment]
https://github.com/mozilla-mobile/android-components/pull/12300 landed and should fix the crashes in 104 - 

We have https://github.com/mozilla/application-services/issues/4639 on file for properly dealing with corrupted databases, looking into the different Sentry messages related to this crash, it seems may are stemming from corrupted databases. I'll flag the corrupted databases bug to the team again and see if we can reprioratize it
