### ISSUE TITLE
FxA(?) - Crashing if no network

### ISSUE THREAD

**Issue by linuxwolf** [mozilla/application-services#501]
Related to mozilla-lockbox/lockbox-android#330

If the device does not have network access to the FxA servers (e.g., airplane mode, network offline, etc), it can crash.  It appears to be in some chain of coroutines and Lockbox has not been able to capture it in code.

From logcat on a Pixel 3XL (Android 9):
```
    --------- beginning of crash
2018-12-21 12:16:54.022 14394-14431/mozilla.lockbox E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: mozilla.lockbox, PID: 14394
    kotlinx.coroutines.CompletionHandlerException: Exception in completion handler InvokeOnCompletion[InvokeOnCompletion@bf725f9] for DeferredCoroutine{Cancelled}@d63393e
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1355)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:292)
        at kotlinx.coroutines.JobSupport.tryFinalizeFinishingState(JobSupport.kt:225)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:792)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:735)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:117)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:45)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
     Caused by: org.mozilla.fxaclient.internal.FxaException$Unspecified: Network error: https://profile.accounts.firefox.com/v1/profile: an error occurred trying to connect: failed to lookup address information: No address associated with hostname
        at org.mozilla.fxaclient.internal.FxaException$Companion.fromConsuming$fxaclient_release(FxaException.kt:25)
        at org.mozilla.fxaclient.internal.FirefoxAccount.getProfile(FirefoxAccount.kt:197)
        at mozilla.components.service.fxa.FirefoxAccount$getProfile$1.invokeSuspend(FirefoxAccount.kt:61)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) 
```

**Comment by vladikoff** [comment]
@linuxwolf, @csadilek landed some changes in ref browser to better handle Offline use cases in https://github.com/mozilla-mobile/reference-browser/blob/d5d5eefa49dcceb698087c5a0f4bc15708fa1ff6/app/src/main/java/org/mozilla/reference/browser/browser/FirefoxAccountsIntegration.kt#L77

(Commit: https://github.com/mozilla-mobile/reference-browser/commit/d5d5eefa49dcceb698087c5a0f4bc15708fa1ff6 )

**Comment by linuxwolf** [comment]
Upgrading to 0.38.0 and explicitly setting the kotlin coroutines dispatcher cleared up all our issues.  Thanks for the help @vladikoff et al
