### ISSUE TITLE
PlacesBookmarksStorage: Error executing SQL: cannot start a transaction within a transaction

### ISSUE THREAD

**Issue by marekchen** [mozilla/application-services#5773]
The following error happend When I run monkey test.
I can't reproduce this error.
It seems occured by calling begin_transaction?

error stack:
Fatal Exception: mozilla.appservices.places.uniffi.PlacesApiException$UnexpectedPlacesException: reason=Error executing SQL: cannot start a transaction within a transaction
       at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.read(FfiConverterTypePlacesApiError.java:144)
       at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.read(FfiConverterTypePlacesApiError.java:144)
       at mozilla.appservices.places.uniffi.FfiConverter$DefaultImpls.liftFromRustBuffer(FfiConverter.java:13)
       at mozilla.appservices.places.uniffi.FfiConverterRustBuffer$DefaultImpls.liftFromRustBuffer(FfiConverterRustBuffer.java:13)
       at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.liftFromRustBuffer(FfiConverterTypePlacesApiError.java)
       at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.liftFromRustBuffer(FfiConverterTypePlacesApiError.java)
       at mozilla.appservices.places.uniffi.FfiConverterRustBuffer$DefaultImpls.lift(FfiConverterRustBuffer.java:8)
       at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.lift(FfiConverterTypePlacesApiError.java:8)
       at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.lift(FfiConverterTypePlacesApiError.java:8)
       at mozilla.appservices.places.uniffi.PlacesApiException$ErrorHandler.lift(PlacesApiException.java:8)
       at mozilla.appservices.places.uniffi.PlacesApiException$ErrorHandler.lift(PlacesApiException.java:8)
       at mozilla.appservices.places.uniffi.PlacesConnection.bookmarksGetTree(PlacesConnection.java:170)
       at mozilla.appservices.places.PlacesReaderConnection.getBookmarksTree(PlacesReaderConnection.java:170)
       at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$getTree$2.invokeSuspend(PlacesBookmarksStorage.java:14)
       at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$getTree$2.invoke(PlacesBookmarksStorage.java:13)
       at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$getTree$2.invoke(PlacesBookmarksStorage.java:13)
       at androidx.fragment.app.FragmentKt.s(Fragment.kt:5)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(BuildersKt__Builders_common.kt:65)
       at kotlinx.coroutines.BuildersKt.withContext(Builders.kt:65)
       at mozilla.components.browser.storage.sync.PlacesBookmarksStorage.getTree$suspendImpl(PlacesBookmarksStorage.java:11)
       at mozilla.components.browser.storage.sync.PlacesBookmarksStorage.getTree(PlacesBookmarksStorage.java:11)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3866)

**Comment by linabutler** [comment]
Hi @marekchen! Could you please provide a full example of how you're calling `PlacesBookmarksStorage.getTree()` in your code? I think this can happen if you're trying to call `getTree` concurrently: `getTree` will start a (read-only) transaction, so if you try to call `getTree` from multiple coroutines at the same time, it'll try to nest the transactions, and fail with that error.

**Comment by marekchen** [comment]
I think  firefox-android has the same issue.
[BookmarkFragment](https://github.com/mozilla-mobile/firefox-android/blob/main/fenix/app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt)'s loadBookmarkNode method and components.core.bookmarksStorage.getTree at [HomeActivity.kt](https://github.com/mozilla-mobile/firefox-android/blob/main/fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt) onPause method maybe run at same time.

**Comment by linabutler** [comment]
Oh! I wasn't aware that [Fenix's `HomeActivity.onPause` was fetching the entire bookmarks tree](https://github.com/mozilla-mobile/firefox-android/blob/a415402dcdaf57c6d71889d696e7a9de496f2850/fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt#L560-L570); thank you so much for catching that! Yes—I think there are definitely a couple of things that we can fix:

**1. Drop the [read-only transaction](https://github.com/mozilla/application-services/blob/d9a3a3f3fe0ea4ed7886d263e80e7fb2bfcdbc75/components/places/src/storage/bookmarks/fetch.rs#L229) in `fetch::fetch_tree_with_depth`.**

IIRC, we originally used one because we had to use [multiple `SELECT`s](https://github.com/mozilla/application-services/blob/56a6764dd23a66bc0391b25693bae4ba879ceebc/components/places/src/storage/bookmarks/public_node.rs#L201-L235) to build the tree—but we fixed that in #1289! 🎉

I quickly looked at [`fetch::fetch_tree_with_depth`](https://github.com/mozilla/application-services/blob/d9a3a3f3fe0ea4ed7886d263e80e7fb2bfcdbc75/components/places/src/storage/bookmarks/fetch.rs#L224-L257), [`json_tree::fetch_tree`](https://github.com/mozilla/application-services/blob/d9a3a3f3fe0ea4ed7886d263e80e7fb2bfcdbc75/components/places/src/storage/bookmarks/json_tree.rs#L489-L670), and all the helper functions they call, and I think we do just one big recursive `SELECT` in `json_tree::fetch_tree` now—so that read-only transaction doesn't seem necessary for consistency anymore.

@mhammond and @skhamis, could you double-check me on that, please? 😊

**2. Add a dedicated API to recursively count the number of descendants in a folder, and have Fenix's `HomeActivity.onPause` use it.**

`getTree(..., true)` works, but it ends up doing a _lot_ of extra work (it has to do a ton of bookkeeping to build the tree structure, which can all be avoided if all we need is the number of bookmarks), and doing all that as the application is going into the background doesn't feel great.
