### ISSUE TITLE
Fenix, with new connection management: SQLITE_BUSY when `noteObservation` overlaps with `sync`.

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#829]
cc @thomcc 
```
03-21 11:26:52.717 32179 32304 E AndroidRuntime: mozilla.appservices.places.PlacesConnectionBusy: Error executing SQL: database is locked
03-21 11:26:52.717 32179 32304 E AndroidRuntime:    at mozilla.appservices.places.RustError.intoException(RustError.kt:50)
03-21 11:26:52.717 32179 32304 E AndroidRuntime:    at mozilla.appservices.places.PlacesWriterConnection.noteObservation(PlacesConnection.kt:702)
03-21 11:26:52.717 32179 32304 E AndroidRuntime:    at mozilla.components.browser.storage.sync.PlacesHistoryStorage$recordVisit$2.invokeSuspend(PlacesHistoryStorage.kt:45)
03-21 11:26:52.717 32179 32304 E AndroidRuntime:    at mozilla.components.browser.storage.sync.PlacesHistoryStorage$recordVisit$2.invoke(Unknown Source:10)
03-21 11:26:52.717 32179 32304 E AndroidRuntime:    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
03-21 11:26:52.717 32179 32304 E AndroidRuntime:    at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:146)
03-21 11:26:52.717 32179 32304 E AndroidRuntime:    at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
03-21 11:26:52.717 32179 32304 E AndroidRuntime:    at mozilla.components.browser.storage.sync.PlacesHistoryStorage.recordVisit$suspendImpl(PlacesHistoryStorage.kt:44)
03-21 11:26:52.717 32179 32304 E AndroidRuntime:    at mozilla.components.browser.storage.sync.PlacesHistoryStorage.recordVisit(Unknown Source:0)
03-21 11:26:52.717 32179 32304 E AndroidRuntime:    at mozilla.components.feature.session.HistoryDelegate.onVisited(HistoryDelegate.kt:21)
03-21 11:26:52.717 32179 32304 E AndroidRuntime:    at mozilla.components.browser.engine.gecko.GeckoEngineSession$createHistoryDelegate$1$onVisited$1.invokeSuspend(GeckoEngineSession.kt:404)
03-21 11:26:52.717 32179 32304 E AndroidRuntime:    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
03-21 11:26:52.717 32179 32304 E AndroidRuntime:    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
03-21 11:26:52.717 32179 32304 E AndroidRuntime:    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
03-21 11:26:52.717 32179 32304 E AndroidRuntime:    at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
03-21 11:26:52.717 32179 32304 E AndroidRuntime:    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

**Comment by thomcc** [comment]
Looks like we never ended up using TimeChunkedTransaction...

**Comment by linacambridge** [comment]
Oh, nice...turns out "database is locked" is `SQLITE_BUSY`, and "database _table_ is locked" is `SQLITE_LOCKED`. 🤨 From `sqlite3ErrStr` in `sqlite3.c`:

```c
/* SQLITE_ABORT       */ "query aborted",
/* SQLITE_BUSY        */ "database is locked",
/* SQLITE_LOCKED      */ "database table is locked",
/* SQLITE_NOMEM       */ "out of memory",
```

We ran into a similar issue with the mirror on Desktop early on. [Bug 1435446](https://bugzilla.mozilla.org/show_bug.cgi?id=1435446), and [this comment in particular](https://bugzilla.mozilla.org/show_bug.cgi?id=1435446#c17), has the gory details.

Places on Desktop handles these by using `IMMEDIATE` transactions—so we'll fail with `SQLITE_BUSY` when we try to run `BEGIN IMMEDIATE`, instead of in the middle of the transaction. When mozStorage gets `SQLITE_BUSY`, it [resets the statement, yields, and tries again](https://searchfox.org/mozilla-central/rev/2c912888e3b7ae4baf161d98d7a01434f31830aa/storage/mozStorageAsyncStatementExecution.cpp#216,236-245).

**Comment by grigoryk** [comment]
@thomcc any updates on this? We're seeing this consistently in both r-b and Fenix.

**Comment by rfk** [comment]
In the interests of sharing context: @mhammond was able to reproduce what we believe to be the issue here, caused by writer thread starvation.  Investigation of a fix are going on in https://github.com/mozilla/application-services/pull/902/
