### ISSUE TITLE
sync15::sync_multiple: Store error: Error executing SQL: UNIQUE constraint failed: temp_sync_updated_meta.id)

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#867]
Seeing this in a local r-b build:

```
03-27 13:33:40.384  4896  4951 D sql_support::conn_ext: Transaction commited after 217.31474ms
03-27 13:33:40.408  4896  4951 W sync15::sync_multiple: Sync of history failed! Error(
03-27 13:33:40.408  4896  4951 W sync15::sync_multiple: 
03-27 13:33:40.408  4896  4951 W sync15::sync_multiple: Store error: Error executing SQL: UNIQUE constraint failed: temp_sync_updated_meta.id)
03-27 13:33:40.408  4896  4951 I sync15::sync_multiple: Updating persisted global state
03-27 13:33:40.411  4896  4951 E places::ffi: Unexpected error: SyncAdapterError(Error(
03-27 13:33:40.411  4896  4951 E places::ffi: 
03-27 13:33:40.411  4896  4951 E places::ffi: Store error: Error executing SQL: UNIQUE constraint failed: temp_sync_updated_meta.id))
03-27 13:33:40.412  4896  4951 E StorageSync: Error synchronizing a history store
03-27 13:33:40.412  4896  4951 E StorageSync: mozilla.appservices.places.PlacesException: Error synchronizing: Store error: Error executing SQL: UNIQUE constraint failed: temp_sync_updated_meta.id
03-27 13:33:40.412  4896  4951 E StorageSync: 	at mozilla.appservices.places.RustError.intoException(RustError.kt:64)
03-27 13:33:40.412  4896  4951 E StorageSync: 	at mozilla.appservices.places.PlacesApi.sync(PlacesConnection.kt:834)
03-27 13:33:40.412  4896  4951 E StorageSync: 	at mozilla.components.browser.storage.sync.RustPlacesConnection.sync(Connection.kt:67)
03-27 13:33:40.412  4896  4951 E StorageSync: 	at mozilla.components.browser.storage.sync.PlacesHistoryStorage.sync$suspendImpl(PlacesHistoryStorage.kt:171)
03-27 13:33:40.412  4896  4951 E StorageSync: 	at mozilla.components.browser.storage.sync.PlacesHistoryStorage.sync(Unknown Source:0)
03-27 13:33:40.412  4896  4951 E StorageSync: 	at mozilla.components.feature.sync.StorageSync.syncStore(StorageSync.kt:73)
03-27 13:33:40.412  4896  4951 E StorageSync: 	at mozilla.components.feature.sync.StorageSync$sync$$inlined$withLock$lambda$1.invokeSuspend(StorageSync.kt:62)
03-27 13:33:40.412  4896  4951 E StorageSync: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
03-27 13:33:40.412  4896  4951 E StorageSync: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
03-27 13:33:40.412  4896  4951 E StorageSync: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
03-27 13:33:40.412  4896  4951 E StorageSync: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
03-27 13:33:40.412  4896  4951 E StorageSync: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

**Comment by thomcc** [comment]
@linacambridge @mhammond https://github.com/mozilla/application-services/blob/1594ff189c503986ea1ef4efd7bfa822fa3a5284/components/places/src/storage/history.rs#L825 should we be doing anything different here (INSERT OR REPLACE maybe?)
